# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .audit_update_attributes import AuditUpdateAttributes
    from .audit_update_data import AuditUpdateData
    from .audit_update_relationships import AuditUpdateRelationships
    from .earned_reward_approved_data import EarnedRewardApprovedData
    from .earned_reward_notification_attributes import EarnedRewardNotificationAttributes
    from .earned_reward_rejected_attributes import EarnedRewardRejectedAttributes
    from .earned_reward_rejected_data import EarnedRewardRejectedData
    from .earned_reward_relationships import EarnedRewardRelationships
    from .earned_reward_settled_attributes import EarnedRewardSettledAttributes
    from .earned_reward_settled_data import EarnedRewardSettledData
    from .email_notification_placement_file_attributes import EmailNotificationPlacementFileAttributes
    from .email_notification_placement_file_data import EmailNotificationPlacementFileData
    from .email_notification_placement_file_relationships import EmailNotificationPlacementFileRelationships
    from .file_result_data import FileResultData
    from .notification_data_union import (
        NotificationDataUnion,
        NotificationDataUnion_AuditUpdate,
        NotificationDataUnion_EarnedRewardApproved,
        NotificationDataUnion_EarnedRewardRejected,
        NotificationDataUnion_EarnedRewardSettled,
        NotificationDataUnion_EmailNotificationPlacementFile,
        NotificationDataUnion_FileProcessingResult,
        NotificationDataUnion_PushNotificationPlacementFile,
    )
    from .notification_metadata import NotificationMetadata
    from .notification_payload import NotificationPayload
    from .push_notification_placement_file_attributes import PushNotificationPlacementFileAttributes
    from .push_notification_placement_file_data import PushNotificationPlacementFileData
    from .push_notification_placement_file_relationships import PushNotificationPlacementFileRelationships
    from .rejected_transaction_relationships import RejectedTransactionRelationships
    from .reward_notification_attributes import RewardNotificationAttributes
    from .user_reward import UserReward
_dynamic_imports: typing.Dict[str, str] = {
    "AuditUpdateAttributes": ".audit_update_attributes",
    "AuditUpdateData": ".audit_update_data",
    "AuditUpdateRelationships": ".audit_update_relationships",
    "EarnedRewardApprovedData": ".earned_reward_approved_data",
    "EarnedRewardNotificationAttributes": ".earned_reward_notification_attributes",
    "EarnedRewardRejectedAttributes": ".earned_reward_rejected_attributes",
    "EarnedRewardRejectedData": ".earned_reward_rejected_data",
    "EarnedRewardRelationships": ".earned_reward_relationships",
    "EarnedRewardSettledAttributes": ".earned_reward_settled_attributes",
    "EarnedRewardSettledData": ".earned_reward_settled_data",
    "EmailNotificationPlacementFileAttributes": ".email_notification_placement_file_attributes",
    "EmailNotificationPlacementFileData": ".email_notification_placement_file_data",
    "EmailNotificationPlacementFileRelationships": ".email_notification_placement_file_relationships",
    "FileResultData": ".file_result_data",
    "NotificationDataUnion": ".notification_data_union",
    "NotificationDataUnion_AuditUpdate": ".notification_data_union",
    "NotificationDataUnion_EarnedRewardApproved": ".notification_data_union",
    "NotificationDataUnion_EarnedRewardRejected": ".notification_data_union",
    "NotificationDataUnion_EarnedRewardSettled": ".notification_data_union",
    "NotificationDataUnion_EmailNotificationPlacementFile": ".notification_data_union",
    "NotificationDataUnion_FileProcessingResult": ".notification_data_union",
    "NotificationDataUnion_PushNotificationPlacementFile": ".notification_data_union",
    "NotificationMetadata": ".notification_metadata",
    "NotificationPayload": ".notification_payload",
    "PushNotificationPlacementFileAttributes": ".push_notification_placement_file_attributes",
    "PushNotificationPlacementFileData": ".push_notification_placement_file_data",
    "PushNotificationPlacementFileRelationships": ".push_notification_placement_file_relationships",
    "RejectedTransactionRelationships": ".rejected_transaction_relationships",
    "RewardNotificationAttributes": ".reward_notification_attributes",
    "UserReward": ".user_reward",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AuditUpdateAttributes",
    "AuditUpdateData",
    "AuditUpdateRelationships",
    "EarnedRewardApprovedData",
    "EarnedRewardNotificationAttributes",
    "EarnedRewardRejectedAttributes",
    "EarnedRewardRejectedData",
    "EarnedRewardRelationships",
    "EarnedRewardSettledAttributes",
    "EarnedRewardSettledData",
    "EmailNotificationPlacementFileAttributes",
    "EmailNotificationPlacementFileData",
    "EmailNotificationPlacementFileRelationships",
    "FileResultData",
    "NotificationDataUnion",
    "NotificationDataUnion_AuditUpdate",
    "NotificationDataUnion_EarnedRewardApproved",
    "NotificationDataUnion_EarnedRewardRejected",
    "NotificationDataUnion_EarnedRewardSettled",
    "NotificationDataUnion_EmailNotificationPlacementFile",
    "NotificationDataUnion_FileProcessingResult",
    "NotificationDataUnion_PushNotificationPlacementFile",
    "NotificationMetadata",
    "NotificationPayload",
    "PushNotificationPlacementFileAttributes",
    "PushNotificationPlacementFileData",
    "PushNotificationPlacementFileRelationships",
    "RejectedTransactionRelationships",
    "RewardNotificationAttributes",
    "UserReward",
]
