# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .audit_update_attributes import AuditUpdateAttributes
    from .audit_update_data import AuditUpdateData
    from .audit_update_relationships import AuditUpdateRelationships
    from .clawback_data import ClawbackData
    from .earned_reward_approved_data import EarnedRewardApprovedData
    from .earned_reward_attributes import EarnedRewardAttributes
    from .earned_reward_relationships import EarnedRewardRelationships
    from .earned_reward_settled_attributes import EarnedRewardSettledAttributes
    from .earned_reward_settled_data import EarnedRewardSettledData
    from .failed_transaction_attributes import FailedTransactionAttributes
    from .failed_transaction_data import FailedTransactionData
    from .failed_transaction_relationships import FailedTransactionRelationships
    from .file_result_data import FileResultData
    from .notification_data_union import (
        NotificationDataUnion,
        NotificationDataUnion_AuditUpdate,
        NotificationDataUnion_Clawback,
        NotificationDataUnion_EarnedRewardApproved,
        NotificationDataUnion_EarnedRewardSettled,
        NotificationDataUnion_FailedTransaction,
        NotificationDataUnion_FileProcessingResult,
        NotificationDataUnion_ValidTransaction,
    )
    from .notification_metadata import NotificationMetadata
    from .notification_payload import NotificationPayload
    from .reward_notification_attributes import RewardNotificationAttributes
    from .transaction_relationships import TransactionRelationships
    from .valid_transaction_attributes import ValidTransactionAttributes
    from .valid_transaction_commission_earned import ValidTransactionCommissionEarned
    from .valid_transaction_data import ValidTransactionData
_dynamic_imports: typing.Dict[str, str] = {
    "AuditUpdateAttributes": ".audit_update_attributes",
    "AuditUpdateData": ".audit_update_data",
    "AuditUpdateRelationships": ".audit_update_relationships",
    "ClawbackData": ".clawback_data",
    "EarnedRewardApprovedData": ".earned_reward_approved_data",
    "EarnedRewardAttributes": ".earned_reward_attributes",
    "EarnedRewardRelationships": ".earned_reward_relationships",
    "EarnedRewardSettledAttributes": ".earned_reward_settled_attributes",
    "EarnedRewardSettledData": ".earned_reward_settled_data",
    "FailedTransactionAttributes": ".failed_transaction_attributes",
    "FailedTransactionData": ".failed_transaction_data",
    "FailedTransactionRelationships": ".failed_transaction_relationships",
    "FileResultData": ".file_result_data",
    "NotificationDataUnion": ".notification_data_union",
    "NotificationDataUnion_AuditUpdate": ".notification_data_union",
    "NotificationDataUnion_Clawback": ".notification_data_union",
    "NotificationDataUnion_EarnedRewardApproved": ".notification_data_union",
    "NotificationDataUnion_EarnedRewardSettled": ".notification_data_union",
    "NotificationDataUnion_FailedTransaction": ".notification_data_union",
    "NotificationDataUnion_FileProcessingResult": ".notification_data_union",
    "NotificationDataUnion_ValidTransaction": ".notification_data_union",
    "NotificationMetadata": ".notification_metadata",
    "NotificationPayload": ".notification_payload",
    "RewardNotificationAttributes": ".reward_notification_attributes",
    "TransactionRelationships": ".transaction_relationships",
    "ValidTransactionAttributes": ".valid_transaction_attributes",
    "ValidTransactionCommissionEarned": ".valid_transaction_commission_earned",
    "ValidTransactionData": ".valid_transaction_data",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AuditUpdateAttributes",
    "AuditUpdateData",
    "AuditUpdateRelationships",
    "ClawbackData",
    "EarnedRewardApprovedData",
    "EarnedRewardAttributes",
    "EarnedRewardRelationships",
    "EarnedRewardSettledAttributes",
    "EarnedRewardSettledData",
    "FailedTransactionAttributes",
    "FailedTransactionData",
    "FailedTransactionRelationships",
    "FileResultData",
    "NotificationDataUnion",
    "NotificationDataUnion_AuditUpdate",
    "NotificationDataUnion_Clawback",
    "NotificationDataUnion_EarnedRewardApproved",
    "NotificationDataUnion_EarnedRewardSettled",
    "NotificationDataUnion_FailedTransaction",
    "NotificationDataUnion_FileProcessingResult",
    "NotificationDataUnion_ValidTransaction",
    "NotificationMetadata",
    "NotificationPayload",
    "RewardNotificationAttributes",
    "TransactionRelationships",
    "ValidTransactionAttributes",
    "ValidTransactionCommissionEarned",
    "ValidTransactionData",
]
