# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...commons.types.purchase_channel import PurchaseChannel
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from ...transactions.types.merchant_asset import MerchantAsset
from .user_reward import UserReward


class EarnedRewardNotificationAttributes(UniversalBaseModel):
    message: str = pydantic.Field()
    """
    The display message associated to the notification
    """

    name: str = pydantic.Field()
    """
    The name of the merchant
    """

    attribution_url: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="attributionUrl"),
        pydantic.Field(
            alias="attributionUrl", description="The attribution URL to track user's interactions with the notification"
        ),
    ]
    survey_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="surveyUrl"),
        pydantic.Field(
            alias="surveyUrl",
            description="Post experience survey URL, if available. This will be present for rewards associated with local offers.",
        ),
    ] = None
    card_product_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="cardProductId"),
        pydantic.Field(alias="cardProductId", description="The ID of the card product"),
    ] = None
    transaction_timestamp: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="transactionTimestamp"),
        pydantic.Field(
            alias="transactionTimestamp", description="The timestamp of the originating transaction in ISO format"
        ),
    ] = None
    transaction_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="transactionId"),
        pydantic.Field(alias="transactionId", description="The transaction ID"),
    ]
    transaction_amount_in_cents: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="transactionAmountInCents"),
        pydantic.Field(
            alias="transactionAmountInCents", description="The amount of the originating transaction in cents"
        ),
    ]
    category_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="categoryName"),
        pydantic.Field(alias="categoryName", description='The category of the offer, e.g. "Food & Dining"'),
    ] = None
    user_reward: typing_extensions.Annotated[
        UserReward,
        FieldMetadata(alias="userReward"),
        pydantic.Field(alias="userReward", description="Type of commission on offer (% or a flat $)"),
    ]
    assets: typing.Optional[typing.List[MerchantAsset]] = pydantic.Field(default=None)
    """
    Tracked asset images for the merchant. The asset
    URL is signed for attribution tracking and should be loaded as-is by the
    client.
    """

    purchase_channel: typing_extensions.Annotated[
        typing.Optional[typing.List[PurchaseChannel]],
        FieldMetadata(alias="purchaseChannel"),
        pydantic.Field(alias="purchaseChannel", description="The purchase channels the offer applies to"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
