# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class EarnedRewardRejectedAttributes(UniversalBaseModel):
    reason: str = pydantic.Field()
    """
    The reason code for why the transaction did not result in a reward
    """

    message: str = pydantic.Field()
    """
    The display message associated to the notification
    """

    transaction_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="transactionId"),
        pydantic.Field(alias="transactionId", description="The transaction ID"),
    ]
    transaction_amount_in_cents: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="transactionAmountInCents"),
        pydantic.Field(
            alias="transactionAmountInCents", description="The amount of the originating transaction in cents"
        ),
    ]
    transaction_timestamp: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="transactionTimestamp"),
        pydantic.Field(
            alias="transactionTimestamp", description="The timestamp of the originating transaction in ISO format"
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
