# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .earned_reward_rejected_attributes import EarnedRewardRejectedAttributes
from .rejected_transaction_relationships import RejectedTransactionRelationships


class EarnedRewardRejectedData(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    The internal ID of the notification
    """

    attributes: EarnedRewardRejectedAttributes
    relationships: RejectedTransactionRelationships

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
