# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...commons.types.purchase_channel import PurchaseChannel
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from ...transactions.types.merchant_asset import MerchantAsset
from .reward_notification_attributes import RewardNotificationAttributes
from .user_reward import UserReward


class EarnedRewardNotificationAttributes(RewardNotificationAttributes):
    category_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="categoryName"),
        pydantic.Field(alias="categoryName", description='The category of the offer, e.g. "Food & Dining"'),
    ] = None
    user_reward: typing_extensions.Annotated[
        typing.Optional[UserReward],
        FieldMetadata(alias="userReward"),
        pydantic.Field(alias="userReward", description="Type of commission on offer (% or a flat $)"),
    ] = None
    assets: typing.Optional[typing.List[MerchantAsset]] = pydantic.Field(default=None)
    """
    Tracked asset images for the merchant. The asset
    URL is signed for attribution tracking and should be loaded as-is by the
    client.
    """

    purchase_channel: typing_extensions.Annotated[
        typing.Optional[typing.List[PurchaseChannel]],
        FieldMetadata(alias="purchaseChannel"),
        pydantic.Field(alias="purchaseChannel", description="The purchase channels the offer applies to"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
