# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .email_notification_placement_file_attributes import EmailNotificationPlacementFileAttributes
from .email_notification_placement_file_relationships import EmailNotificationPlacementFileRelationships


class EmailNotificationPlacementFileData(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    The placement ID, also used as the notification resource ID
    """

    attributes: EmailNotificationPlacementFileAttributes
    relationships: EmailNotificationPlacementFileRelationships

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
