# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...files.types.file_metadata_attribute import FileMetadataAttribute
from .audit_update_attributes import AuditUpdateAttributes
from .audit_update_relationships import AuditUpdateRelationships
from .earned_reward_attributes import EarnedRewardAttributes
from .earned_reward_relationships import EarnedRewardRelationships
from .earned_reward_settled_attributes import EarnedRewardSettledAttributes
from .failed_transaction_attributes import FailedTransactionAttributes
from .failed_transaction_relationships import FailedTransactionRelationships
from .transaction_relationships import TransactionRelationships
from .valid_transaction_attributes import ValidTransactionAttributes


class NotificationDataUnion_EarnedRewardApproved(UniversalBaseModel):
    type: typing.Literal["earnedRewardApproved"] = "earnedRewardApproved"
    id: str
    attributes: EarnedRewardAttributes
    relationships: EarnedRewardRelationships

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class NotificationDataUnion_EarnedRewardSettled(UniversalBaseModel):
    type: typing.Literal["earnedRewardSettled"] = "earnedRewardSettled"
    id: str
    attributes: EarnedRewardSettledAttributes
    relationships: EarnedRewardRelationships

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class NotificationDataUnion_ValidTransaction(UniversalBaseModel):
    type: typing.Literal["validTransaction"] = "validTransaction"
    id: str
    attributes: ValidTransactionAttributes
    relationships: TransactionRelationships

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class NotificationDataUnion_FailedTransaction(UniversalBaseModel):
    type: typing.Literal["failedTransaction"] = "failedTransaction"
    id: str
    attributes: FailedTransactionAttributes
    relationships: FailedTransactionRelationships

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class NotificationDataUnion_Clawback(UniversalBaseModel):
    type: typing.Literal["clawback"] = "clawback"
    id: str
    attributes: FailedTransactionAttributes
    relationships: FailedTransactionRelationships

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class NotificationDataUnion_AuditUpdate(UniversalBaseModel):
    type: typing.Literal["auditUpdate"] = "auditUpdate"
    id: str
    attributes: AuditUpdateAttributes
    relationships: AuditUpdateRelationships

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class NotificationDataUnion_FileProcessingResult(UniversalBaseModel):
    type: typing.Literal["fileProcessingResult"] = "fileProcessingResult"
    id: str
    attributes: FileMetadataAttribute

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


NotificationDataUnion = typing_extensions.Annotated[
    typing.Union[
        NotificationDataUnion_EarnedRewardApproved,
        NotificationDataUnion_EarnedRewardSettled,
        NotificationDataUnion_ValidTransaction,
        NotificationDataUnion_FailedTransaction,
        NotificationDataUnion_Clawback,
        NotificationDataUnion_AuditUpdate,
        NotificationDataUnion_FileProcessingResult,
    ],
    pydantic.Field(discriminator="type"),
]
