# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...files.types.file_metadata_attribute import FileMetadataAttribute
from .audit_update_attributes import AuditUpdateAttributes
from .audit_update_relationships import AuditUpdateRelationships
from .earned_reward_notification_attributes import EarnedRewardNotificationAttributes
from .earned_reward_rejected_attributes import EarnedRewardRejectedAttributes
from .earned_reward_relationships import EarnedRewardRelationships
from .earned_reward_settled_attributes import EarnedRewardSettledAttributes
from .email_notification_placement_file_attributes import EmailNotificationPlacementFileAttributes
from .email_notification_placement_file_relationships import EmailNotificationPlacementFileRelationships
from .push_notification_placement_file_attributes import PushNotificationPlacementFileAttributes
from .push_notification_placement_file_relationships import PushNotificationPlacementFileRelationships
from .rejected_transaction_relationships import RejectedTransactionRelationships


class NotificationDataUnion_EarnedRewardApproved(UniversalBaseModel):
    type: typing.Literal["earnedRewardApproved"] = "earnedRewardApproved"
    id: str
    attributes: EarnedRewardNotificationAttributes
    relationships: EarnedRewardRelationships

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class NotificationDataUnion_EarnedRewardSettled(UniversalBaseModel):
    type: typing.Literal["earnedRewardSettled"] = "earnedRewardSettled"
    id: str
    attributes: EarnedRewardSettledAttributes
    relationships: EarnedRewardRelationships

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class NotificationDataUnion_EarnedRewardRejected(UniversalBaseModel):
    type: typing.Literal["earnedRewardRejected"] = "earnedRewardRejected"
    id: str
    attributes: EarnedRewardRejectedAttributes
    relationships: RejectedTransactionRelationships

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class NotificationDataUnion_AuditUpdate(UniversalBaseModel):
    type: typing.Literal["auditUpdate"] = "auditUpdate"
    id: str
    attributes: AuditUpdateAttributes
    relationships: AuditUpdateRelationships

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class NotificationDataUnion_FileProcessingResult(UniversalBaseModel):
    type: typing.Literal["fileProcessingResult"] = "fileProcessingResult"
    id: str
    attributes: FileMetadataAttribute

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class NotificationDataUnion_PushNotificationPlacementFile(UniversalBaseModel):
    type: typing.Literal["pushNotificationPlacementFile"] = "pushNotificationPlacementFile"
    id: str
    attributes: PushNotificationPlacementFileAttributes
    relationships: PushNotificationPlacementFileRelationships

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class NotificationDataUnion_EmailNotificationPlacementFile(UniversalBaseModel):
    type: typing.Literal["emailNotificationPlacementFile"] = "emailNotificationPlacementFile"
    id: str
    attributes: EmailNotificationPlacementFileAttributes
    relationships: EmailNotificationPlacementFileRelationships

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


NotificationDataUnion = typing_extensions.Annotated[
    typing.Union[
        NotificationDataUnion_EarnedRewardApproved,
        NotificationDataUnion_EarnedRewardSettled,
        NotificationDataUnion_EarnedRewardRejected,
        NotificationDataUnion_AuditUpdate,
        NotificationDataUnion_FileProcessingResult,
        NotificationDataUnion_PushNotificationPlacementFile,
        NotificationDataUnion_EmailNotificationPlacementFile,
    ],
    pydantic.Field(discriminator="type"),
]
