# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class PushNotificationPlacementFileAttributes(UniversalBaseModel):
    placement_name: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="placementName"),
        pydantic.Field(alias="placementName", description="The display name of the placement"),
    ]
    available_slots: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="availableSlots"),
        pydantic.Field(alias="availableSlots", description="The number of offer slots available in the placement"),
    ]
    cadence: str = pydantic.Field()
    """
    The delivery cadence of the placement (e.g. WEEKLY)
    """

    download_url: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="downloadUrl"),
        pydantic.Field(
            alias="downloadUrl", description="Presigned URL to download the generated placement file (gzipped JSONL)"
        ),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
