# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .push_notification_placement_file_attributes import PushNotificationPlacementFileAttributes
from .push_notification_placement_file_relationships import PushNotificationPlacementFileRelationships


class PushNotificationPlacementFileData(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    The placement ID, also used as the notification resource ID
    """

    attributes: PushNotificationPlacementFileAttributes
    relationships: PushNotificationPlacementFileRelationships

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
