# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class RewardNotificationAttributes(UniversalBaseModel):
    message: str = pydantic.Field()
    """
    The display message associated to the notification
    """

    name: str = pydantic.Field()
    """
    The name of the merchant
    """

    attribution_url: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="attributionUrl"),
        pydantic.Field(
            alias="attributionUrl", description="The attribution URL to track user's interactions with the notification"
        ),
    ]
    survey_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="surveyUrl"),
        pydantic.Field(
            alias="surveyUrl",
            description="Post experience survey URL, if available. This will be present for rewards associated with local offers.",
        ),
    ] = None
    card_product_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="cardProductId"),
        pydantic.Field(alias="cardProductId", description="The ID of the card product"),
    ] = None
    transaction_timestamp: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="transactionTimestamp"),
        pydantic.Field(
            alias="transactionTimestamp", description="The timestamp of the originating transaction in ISO format"
        ),
    ] = None
    transaction_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="transactionId"),
        pydantic.Field(alias="transactionId", description="The transaction ID"),
    ]
    transaction_amount_in_cents: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="transactionAmountInCents"),
        pydantic.Field(
            alias="transactionAmountInCents", description="The amount of the originating transaction in cents"
        ),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
