# This file was auto-generated by Fern from our API Definition.

import typing

FileType = typing.Union[
    typing.Literal[
        "earnedRewardApprovedDailyReconciliationFile",
        "earnedRewardSettledDailyReconciliationFile",
        "monthlyReconciliationFile",
    ],
    typing.Any,
]
