# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        AuditUpdateAttributes,
        AuditUpdateData,
        AuditUpdateRelationships,
        ClawbackData,
        EarnedRewardApprovedData,
        EarnedRewardAttributes,
        EarnedRewardRelationships,
        EarnedRewardSettledAttributes,
        EarnedRewardSettledData,
        FailedTransactionAttributes,
        FailedTransactionData,
        FailedTransactionRelationships,
        FileResultData,
        NotificationDataUnion,
        NotificationDataUnion_AuditUpdate,
        NotificationDataUnion_Clawback,
        NotificationDataUnion_EarnedRewardApproved,
        NotificationDataUnion_EarnedRewardSettled,
        NotificationDataUnion_FailedTransaction,
        NotificationDataUnion_FileProcessingResult,
        NotificationDataUnion_ValidTransaction,
        NotificationMetadata,
        NotificationPayload,
        RewardNotificationAttributes,
        TransactionRelationships,
        ValidTransactionAttributes,
        ValidTransactionCommissionEarned,
        ValidTransactionData,
    )
    from . import subscriptions
    from .subscriptions import (
        CreateSubscriptionUnion,
        CreateSubscriptionUnion_Subscription,
        CreateSubscriptionsResponseObject,
        CreatedSubscription,
        Subscription,
        SubscriptionAttributes,
        SubscriptionRequest,
        SubscriptionRequestAttributes,
        SubscriptionRequestBody,
        SubscriptionRequestUnion,
        SubscriptionRequestUnion_Subscription,
        SubscriptionUnion,
        SubscriptionUnion_Subscription,
        SubscriptionsResponseObject,
        UpdateSubscriptionRequest,
        UpdateSubscriptionRequestAttributes,
        UpdateSubscriptionRequestBody,
        UpdateSubscriptionRequestUnion,
        UpdateSubscriptionRequestUnion_Subscription,
        UpdateSubscriptionsResponseObject,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "AuditUpdateAttributes": ".types",
    "AuditUpdateData": ".types",
    "AuditUpdateRelationships": ".types",
    "ClawbackData": ".types",
    "CreateSubscriptionUnion": ".subscriptions",
    "CreateSubscriptionUnion_Subscription": ".subscriptions",
    "CreateSubscriptionsResponseObject": ".subscriptions",
    "CreatedSubscription": ".subscriptions",
    "EarnedRewardApprovedData": ".types",
    "EarnedRewardAttributes": ".types",
    "EarnedRewardRelationships": ".types",
    "EarnedRewardSettledAttributes": ".types",
    "EarnedRewardSettledData": ".types",
    "FailedTransactionAttributes": ".types",
    "FailedTransactionData": ".types",
    "FailedTransactionRelationships": ".types",
    "FileResultData": ".types",
    "NotificationDataUnion": ".types",
    "NotificationDataUnion_AuditUpdate": ".types",
    "NotificationDataUnion_Clawback": ".types",
    "NotificationDataUnion_EarnedRewardApproved": ".types",
    "NotificationDataUnion_EarnedRewardSettled": ".types",
    "NotificationDataUnion_FailedTransaction": ".types",
    "NotificationDataUnion_FileProcessingResult": ".types",
    "NotificationDataUnion_ValidTransaction": ".types",
    "NotificationMetadata": ".types",
    "NotificationPayload": ".types",
    "RewardNotificationAttributes": ".types",
    "Subscription": ".subscriptions",
    "SubscriptionAttributes": ".subscriptions",
    "SubscriptionRequest": ".subscriptions",
    "SubscriptionRequestAttributes": ".subscriptions",
    "SubscriptionRequestBody": ".subscriptions",
    "SubscriptionRequestUnion": ".subscriptions",
    "SubscriptionRequestUnion_Subscription": ".subscriptions",
    "SubscriptionUnion": ".subscriptions",
    "SubscriptionUnion_Subscription": ".subscriptions",
    "SubscriptionsResponseObject": ".subscriptions",
    "TransactionRelationships": ".types",
    "UpdateSubscriptionRequest": ".subscriptions",
    "UpdateSubscriptionRequestAttributes": ".subscriptions",
    "UpdateSubscriptionRequestBody": ".subscriptions",
    "UpdateSubscriptionRequestUnion": ".subscriptions",
    "UpdateSubscriptionRequestUnion_Subscription": ".subscriptions",
    "UpdateSubscriptionsResponseObject": ".subscriptions",
    "ValidTransactionAttributes": ".types",
    "ValidTransactionCommissionEarned": ".types",
    "ValidTransactionData": ".types",
    "subscriptions": ".subscriptions",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AuditUpdateAttributes",
    "AuditUpdateData",
    "AuditUpdateRelationships",
    "ClawbackData",
    "CreateSubscriptionUnion",
    "CreateSubscriptionUnion_Subscription",
    "CreateSubscriptionsResponseObject",
    "CreatedSubscription",
    "EarnedRewardApprovedData",
    "EarnedRewardAttributes",
    "EarnedRewardRelationships",
    "EarnedRewardSettledAttributes",
    "EarnedRewardSettledData",
    "FailedTransactionAttributes",
    "FailedTransactionData",
    "FailedTransactionRelationships",
    "FileResultData",
    "NotificationDataUnion",
    "NotificationDataUnion_AuditUpdate",
    "NotificationDataUnion_Clawback",
    "NotificationDataUnion_EarnedRewardApproved",
    "NotificationDataUnion_EarnedRewardSettled",
    "NotificationDataUnion_FailedTransaction",
    "NotificationDataUnion_FileProcessingResult",
    "NotificationDataUnion_ValidTransaction",
    "NotificationMetadata",
    "NotificationPayload",
    "RewardNotificationAttributes",
    "Subscription",
    "SubscriptionAttributes",
    "SubscriptionRequest",
    "SubscriptionRequestAttributes",
    "SubscriptionRequestBody",
    "SubscriptionRequestUnion",
    "SubscriptionRequestUnion_Subscription",
    "SubscriptionUnion",
    "SubscriptionUnion_Subscription",
    "SubscriptionsResponseObject",
    "TransactionRelationships",
    "UpdateSubscriptionRequest",
    "UpdateSubscriptionRequestAttributes",
    "UpdateSubscriptionRequestBody",
    "UpdateSubscriptionRequestUnion",
    "UpdateSubscriptionRequestUnion_Subscription",
    "UpdateSubscriptionsResponseObject",
    "ValidTransactionAttributes",
    "ValidTransactionCommissionEarned",
    "ValidTransactionData",
    "subscriptions",
]
