# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .activate_offer_include_option import ActivateOfferIncludeOption
    from .activate_offer_included import ActivateOfferIncluded
    from .activate_offer_response import ActivateOfferResponse
    from .activate_offer_response_attributes import ActivateOfferResponseAttributes
    from .activate_offer_response_data import ActivateOfferResponseData
    from .create_attribution_request_object import CreateAttributionRequestObject
    from .create_attribution_request_union import (
        CreateAttributionRequestUnion,
        CreateAttributionRequestUnion_NotificationAttribution,
        CreateAttributionRequestUnion_OfferAttribution,
    )
    from .create_attribution_response import CreateAttributionResponse
    from .event_code import EventCode
    from .notification_attribution_attributes import NotificationAttributionAttributes
    from .notification_attribution_request import NotificationAttributionRequest
    from .notification_medium import NotificationMedium
    from .offer_attribution_attributes import OfferAttributionAttributes
    from .offer_attribution_request import OfferAttributionRequest
    from .offer_medium import OfferMedium
_dynamic_imports: typing.Dict[str, str] = {
    "ActivateOfferIncludeOption": ".activate_offer_include_option",
    "ActivateOfferIncluded": ".activate_offer_included",
    "ActivateOfferResponse": ".activate_offer_response",
    "ActivateOfferResponseAttributes": ".activate_offer_response_attributes",
    "ActivateOfferResponseData": ".activate_offer_response_data",
    "CreateAttributionRequestObject": ".create_attribution_request_object",
    "CreateAttributionRequestUnion": ".create_attribution_request_union",
    "CreateAttributionRequestUnion_NotificationAttribution": ".create_attribution_request_union",
    "CreateAttributionRequestUnion_OfferAttribution": ".create_attribution_request_union",
    "CreateAttributionResponse": ".create_attribution_response",
    "EventCode": ".event_code",
    "NotificationAttributionAttributes": ".notification_attribution_attributes",
    "NotificationAttributionRequest": ".notification_attribution_request",
    "NotificationMedium": ".notification_medium",
    "OfferAttributionAttributes": ".offer_attribution_attributes",
    "OfferAttributionRequest": ".offer_attribution_request",
    "OfferMedium": ".offer_medium",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ActivateOfferIncludeOption",
    "ActivateOfferIncluded",
    "ActivateOfferResponse",
    "ActivateOfferResponseAttributes",
    "ActivateOfferResponseData",
    "CreateAttributionRequestObject",
    "CreateAttributionRequestUnion",
    "CreateAttributionRequestUnion_NotificationAttribution",
    "CreateAttributionRequestUnion_OfferAttribution",
    "CreateAttributionResponse",
    "EventCode",
    "NotificationAttributionAttributes",
    "NotificationAttributionRequest",
    "NotificationMedium",
    "OfferAttributionAttributes",
    "OfferAttributionRequest",
    "OfferMedium",
]
