# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .activate_placement_slot_response_data import ActivatePlacementSlotResponseData


class ActivatePlacementSlotResponse(UniversalBaseModel):
    """
    Ack payload for a slot activation request.

    Examples
    --------
    import datetime

    from kard.users.attributions import (
        ActivatePlacementSlotResponse,
        ActivatePlacementSlotResponseAttributes,
        ActivatePlacementSlotResponseData,
    )

    ActivatePlacementSlotResponse(
        data=ActivatePlacementSlotResponseData(
            type="placementSlotAttribution",
            id="c94a93a7-beb9-4e58-960c-2c812f849398",
            attributes=ActivatePlacementSlotResponseAttributes(
                placement_id="018f8d6b-1abc-7def-9012-345678901234",
                slot_id="slot-a",
                event_code="ACTIVATE",
                medium="CTA",
                event_date=datetime.datetime.fromisoformat(
                    "2025-01-01 00:00:00+00:00",
                ),
                offer_ids=["offer-1", "offer-2", "offer-3"],
            ),
        ),
    )
    """

    data: ActivatePlacementSlotResponseData

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
