# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .activate_offer_included import ActivateOfferIncluded
from .activate_offer_response_data import ActivateOfferResponseData


class ActivateOfferResponse(UniversalBaseModel):
    """
    Examples
    --------
    import datetime

    from kard.users.attributions import (
        ActivateOfferResponse,
        ActivateOfferResponseAttributes,
        ActivateOfferResponseData,
    )

    ActivateOfferResponse(
        data=ActivateOfferResponseData(
            type="offerAttribution",
            id="c94a93a7-beb9-4e58-960c-2c812f849398",
            attributes=ActivateOfferResponseAttributes(
                entity_id="offer-456",
                event_code="ACTIVATE",
                medium="CTA",
                event_date=datetime.datetime.fromisoformat(
                    "2025-01-01 00:00:00+00:00",
                ),
            ),
        ),
    )
    """

    data: ActivateOfferResponseData
    included: typing.Optional[typing.List[ActivateOfferIncluded]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
