# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata


class ActivatePlacementSlotResponseAttributes(UniversalBaseModel):
    placement_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="placementId"),
        pydantic.Field(alias="placementId", description="Unique identifier of the placement"),
    ]
    slot_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="slotId"),
        pydantic.Field(alias="slotId", description="Stable identifier for the slot within the placement"),
    ]
    event_code: typing_extensions.Annotated[str, FieldMetadata(alias="eventCode"), pydantic.Field(alias="eventCode")]
    medium: str
    event_date: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="eventDate"), pydantic.Field(alias="eventDate")
    ]
    offer_ids: typing_extensions.Annotated[
        typing.List[str],
        FieldMetadata(alias="offerIds"),
        pydantic.Field(
            alias="offerIds",
            description="All offer IDs that resolved under the slot's content strategy and had\nper-offer `offerAttribution` ACTIVATE events written. The partner can use\nthis to render the batch immediately without an extra round-trip.",
        ),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
