# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .activate_placement_slot_response_attributes import ActivatePlacementSlotResponseAttributes


class ActivatePlacementSlotResponseData(UniversalBaseModel):
    type: str
    id: str = pydantic.Field()
    """
    The slot-level attribution event id
    """

    attributes: ActivatePlacementSlotResponseAttributes

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
