# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .attribution_filter import AttributionFilter


class AttributionState(UniversalBaseModel):
    rank: typing.Optional[int] = pydantic.Field(default=None)
    """
    The position of the offer in the list shown to the user (1-indexed)
    """

    filters: typing.Optional[typing.List[AttributionFilter]] = pydantic.Field(default=None)
    """
    The active filters when the user saw the offer
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
