# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from .attribution_filter import AttributionFilter


class AttributionState(UniversalBaseModel):
    rank: typing.Optional[int] = pydantic.Field(default=None)
    """
    The position of the offer in the list shown to the user (1-indexed)
    """

    filters: typing.Optional[typing.List[AttributionFilter]] = pydantic.Field(default=None)
    """
    The active filters when the user saw the offer
    """

    placement_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="placementId"),
        pydantic.Field(
            alias="placementId", description="Unique identifier of the placement the attribution event originated from"
        ),
    ] = None
    slot_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="slotId"),
        pydantic.Field(alias="slotId", description="Stable identifier for the slot within the placement"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
