# This file was auto-generated by Fern from our API Definition.

import typing

from ...rewards.types.category_included import CategoryIncluded
from ...rewards.types.offer_data_union import OfferDataUnion

BoostOfferIncluded = typing.Union[OfferDataUnion, CategoryIncluded]
