# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .boost_offer_included import BoostOfferIncluded
from .boost_offer_response_data import BoostOfferResponseData


class BoostOfferResponse(UniversalBaseModel):
    """
    Examples
    --------
    import datetime

    from kard.users.attributions import (
        BoostOfferResponse,
        BoostOfferResponseAttributes,
        BoostOfferResponseData,
    )

    BoostOfferResponse(
        data=BoostOfferResponseData(
            type="offerAttribution",
            id="c94a93a7-beb9-4e58-960c-2c812f849398",
            attributes=BoostOfferResponseAttributes(
                entity_id="offer-456",
                event_code="BOOST",
                medium="CTA",
                event_date=datetime.datetime.fromisoformat(
                    "2025-01-01 00:00:00+00:00",
                ),
            ),
        ),
    )
    """

    data: BoostOfferResponseData
    included: typing.Optional[typing.List[BoostOfferIncluded]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
