# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import ExternalOrganizationAttributes, ExternalOrganizationResponse
    from . import children, placements
    from .children import (
        ChildOrganizationListResponse,
        CreateChildAttributes,
        CreateChildRequestBody,
        CreateChildRequestData,
        UpdateChildAttributes,
        UpdateChildRequestBody,
        UpdateChildRequestData,
    )
    from .placements import (
        Cadence,
        CadenceFrequency,
        CreateMainPageAttributes,
        CreateMainPagePlacementData,
        CreatePlacementDataUnion,
        CreatePlacementDataUnion_PlacementMainPage,
        CreatePlacementDataUnion_PlacementPushNotification,
        CreatePlacementRequestBody,
        CreatePushNotificationAttributes,
        CreatePushNotificationPlacementData,
        DayOfWeek,
        MainPagePlacementAttributes,
        MainPagePlacementData,
        PlacementFormatUnion,
        PlacementFormatUnion_PlacementMainPage,
        PlacementFormatUnion_PlacementPushNotification,
        PlacementListResponse,
        PushNotificationPlacementAttributes,
        PushNotificationPlacementData,
        UpdateMainPageAttributes,
        UpdateMainPagePlacementData,
        UpdatePlacementDataUnion,
        UpdatePlacementDataUnion_PlacementMainPage,
        UpdatePlacementDataUnion_PlacementPushNotification,
        UpdatePlacementRequestBody,
        UpdatePushNotificationAttributes,
        UpdatePushNotificationPlacementData,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "Cadence": ".placements",
    "CadenceFrequency": ".placements",
    "ChildOrganizationListResponse": ".children",
    "CreateChildAttributes": ".children",
    "CreateChildRequestBody": ".children",
    "CreateChildRequestData": ".children",
    "CreateMainPageAttributes": ".placements",
    "CreateMainPagePlacementData": ".placements",
    "CreatePlacementDataUnion": ".placements",
    "CreatePlacementDataUnion_PlacementMainPage": ".placements",
    "CreatePlacementDataUnion_PlacementPushNotification": ".placements",
    "CreatePlacementRequestBody": ".placements",
    "CreatePushNotificationAttributes": ".placements",
    "CreatePushNotificationPlacementData": ".placements",
    "DayOfWeek": ".placements",
    "ExternalOrganizationAttributes": ".types",
    "ExternalOrganizationResponse": ".types",
    "MainPagePlacementAttributes": ".placements",
    "MainPagePlacementData": ".placements",
    "PlacementFormatUnion": ".placements",
    "PlacementFormatUnion_PlacementMainPage": ".placements",
    "PlacementFormatUnion_PlacementPushNotification": ".placements",
    "PlacementListResponse": ".placements",
    "PushNotificationPlacementAttributes": ".placements",
    "PushNotificationPlacementData": ".placements",
    "UpdateChildAttributes": ".children",
    "UpdateChildRequestBody": ".children",
    "UpdateChildRequestData": ".children",
    "UpdateMainPageAttributes": ".placements",
    "UpdateMainPagePlacementData": ".placements",
    "UpdatePlacementDataUnion": ".placements",
    "UpdatePlacementDataUnion_PlacementMainPage": ".placements",
    "UpdatePlacementDataUnion_PlacementPushNotification": ".placements",
    "UpdatePlacementRequestBody": ".placements",
    "UpdatePushNotificationAttributes": ".placements",
    "UpdatePushNotificationPlacementData": ".placements",
    "children": ".children",
    "placements": ".placements",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "Cadence",
    "CadenceFrequency",
    "ChildOrganizationListResponse",
    "CreateChildAttributes",
    "CreateChildRequestBody",
    "CreateChildRequestData",
    "CreateMainPageAttributes",
    "CreateMainPagePlacementData",
    "CreatePlacementDataUnion",
    "CreatePlacementDataUnion_PlacementMainPage",
    "CreatePlacementDataUnion_PlacementPushNotification",
    "CreatePlacementRequestBody",
    "CreatePushNotificationAttributes",
    "CreatePushNotificationPlacementData",
    "DayOfWeek",
    "ExternalOrganizationAttributes",
    "ExternalOrganizationResponse",
    "MainPagePlacementAttributes",
    "MainPagePlacementData",
    "PlacementFormatUnion",
    "PlacementFormatUnion_PlacementMainPage",
    "PlacementFormatUnion_PlacementPushNotification",
    "PlacementListResponse",
    "PushNotificationPlacementAttributes",
    "PushNotificationPlacementData",
    "UpdateChildAttributes",
    "UpdateChildRequestBody",
    "UpdateChildRequestData",
    "UpdateMainPageAttributes",
    "UpdateMainPagePlacementData",
    "UpdatePlacementDataUnion",
    "UpdatePlacementDataUnion_PlacementMainPage",
    "UpdatePlacementDataUnion_PlacementPushNotification",
    "UpdatePlacementRequestBody",
    "UpdatePushNotificationAttributes",
    "UpdatePushNotificationPlacementData",
    "children",
    "placements",
]
