# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .approved_transaction_attributes import ApprovedTransactionAttributes
from .rewarded_transaction_relationships import RewardedTransactionRelationships


class ApprovedTransaction(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Unique transaction identifier
    """

    attributes: ApprovedTransactionAttributes
    relationships: RewardedTransactionRelationships

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
