# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class ApprovedTransactionAttributes(UniversalBaseModel):
    status: typing.Literal["APPROVED"] = pydantic.Field(default="APPROVED")
    """
    Status of the approved transaction
    """

    transaction_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="transactionId"),
        pydantic.Field(alias="transactionId", description="The transaction identifier"),
    ]
    transaction_amount_in_cents: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="transactionAmountInCents"),
        pydantic.Field(alias="transactionAmountInCents", description="Transaction amount in cents"),
    ]
    transaction_timestamp: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="transactionTimestamp"),
        pydantic.Field(alias="transactionTimestamp", description="Timestamp of the transaction in ISO 8601 format"),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
