# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .core_transaction_attributes import CoreTransactionAttributes


class CoreTransactionRequest(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Unique identifier for the transaction event. This <b>must</b> be unique for each distinct event sent to the API.
    """

    attributes: CoreTransactionAttributes

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
