# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .direction_type import DirectionType


class CoreTransactionAttributes(UniversalBaseModel):
    user_id: typing_extensions.Annotated[str, FieldMetadata(alias="userId")] = pydantic.Field()
    """
    The ID of the user as defined on the issuers system
    """

    transaction_id: typing_extensions.Annotated[str, FieldMetadata(alias="transactionId")] = pydantic.Field()
    """
    The transaction ID from the core banking system
    """

    amount: int = pydantic.Field()
    """
    Transaction amount in cents
    """

    currency: str = pydantic.Field()
    """
    Currency of transaction in ISO 4217 alpha-3 format
    """

    description: str = pydantic.Field()
    """
    Description of transaction - usually includes merchant and other key details on transaction
    """

    direction: DirectionType = pydantic.Field()
    """
    The direction in which the funds flow - DEBIT or CREDIT
    """

    status: typing.Literal["SETTLED"] = pydantic.Field(default="SETTLED")
    """
    Transaction status (always SETTLED for core transactions)
    """

    settled_date: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="settledDate")] = pydantic.Field()
    """
    Timestamp when transaction was settled. Date string should be in ISO 8601 format i.e.'YYYY-MM-DDThh:mm:ss.sTZD' where TZD = time zone designator (Z or +hh:mm or -hh:mm) i.e. 1994-11-05T08:15:30-05:00 OR 1994-11-05T08:15:30Z
    """

    authorization_date: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="authorizationDate")] = (
        pydantic.Field()
    )
    """
    Timestamp for transaction authorization. Date string should be in ISO 8601 format i.e.'YYYY-MM-DDThh:mm:ss.sTZD' where TZD = time zone designator (Z or +hh:mm or -hh:mm) i.e. 1994-11-05T08:15:30-05:00 OR 1994-11-05T08:15:30Z
    """

    financial_institution_name: typing_extensions.Annotated[str, FieldMetadata(alias="financialInstitutionName")] = (
        pydantic.Field()
    )
    """
    Name of the financial institution
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
