# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_file_upload_data import CreateFileUploadData


class CreateFileUploadRequestBody(UniversalBaseModel):
    data: typing.List[CreateFileUploadData] = pydantic.Field()
    """
    List of file upload requests (1–10 items per request).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
