# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .file_upload_url_data import FileUploadUrlData


class CreateFileUploadUrlResponse(UniversalBaseModel):
    """
    Examples
    --------
    from kard.transactions import (
        CreateFileUploadUrlResponse,
        FileUploadUrlAttributes,
        FileUploadUrlData,
    )

    CreateFileUploadUrlResponse(
        data=[
            FileUploadUrlData(
                id="2NxKz7TYmqVH8UrjGP1xK3hF2gs",
                attributes=FileUploadUrlAttributes(
                    url="https://s3.amazonaws.com/bucket/key1?X-Amz-Algorithm=...",
                    expires_in=900,
                ),
            ),
            FileUploadUrlData(
                id="3PqLa8UZnrWI9VskHQ2yL4iG3ht",
                attributes=FileUploadUrlAttributes(
                    url="https://s3.amazonaws.com/bucket/key2?X-Amz-Algorithm=...",
                    expires_in=900,
                ),
            ),
        ],
    )
    """

    data: typing.List[FileUploadUrlData] = pydantic.Field()
    """
    List of created file upload sessions.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
