# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .file_upload_url_attributes import FileUploadUrlAttributes


class FileUploadUrlData(UniversalBaseModel):
    type: typing.Literal["incomingTransactionsFile"] = "incomingTransactionsFile"
    id: str = pydantic.Field()
    """
    Upload session ID for traceability
    """

    attributes: FileUploadUrlAttributes

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
