# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class FinancialInstitution(UniversalBaseModel):
    rssd_id: typing_extensions.Annotated[str, FieldMetadata(alias="rssdId")] = pydantic.Field()
    """
    Research, Statistics, Supervision, Discount ID (RSSD) - Federal Reserve identifier for financial institutions
    """

    name: str = pydantic.Field()
    """
    Name of the financial institution
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
