# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .approved_transaction_attributes import ApprovedTransactionAttributes
from .rewarded_transaction_attributes import RewardedTransactionAttributes
from .rewarded_transaction_relationships import RewardedTransactionRelationships


class RewardedTransactionUnion_RewardedTransaction(UniversalBaseModel):
    type: typing.Literal["rewardedTransaction"] = "rewardedTransaction"
    id: str
    attributes: RewardedTransactionAttributes
    relationships: RewardedTransactionRelationships

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class RewardedTransactionUnion_ApprovedTransaction(UniversalBaseModel):
    type: typing.Literal["approvedTransaction"] = "approvedTransaction"
    id: str
    attributes: ApprovedTransactionAttributes
    relationships: RewardedTransactionRelationships

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


RewardedTransactionUnion = typing_extensions.Annotated[
    typing.Union[RewardedTransactionUnion_RewardedTransaction, RewardedTransactionUnion_ApprovedTransaction],
    pydantic.Field(discriminator="type"),
]
