# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...commons.types.offer_components import OfferComponents
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .commission_earned_details import CommissionEarnedDetails
from .payment_status import PaymentStatus


class RewardedTransactionAttributes(UniversalBaseModel):
    status: typing.Literal["SETTLED"] = pydantic.Field(default="SETTLED")
    """
    Status of the rewarded transaction
    """

    transaction_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="transactionId"),
        pydantic.Field(alias="transactionId", description="The transaction identifier"),
    ]
    transaction_amount_in_cents: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="transactionAmountInCents"),
        pydantic.Field(alias="transactionAmountInCents", description="Transaction amount in cents"),
    ]
    transaction_timestamp: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="transactionTimestamp"),
        pydantic.Field(alias="transactionTimestamp", description="Timestamp of the transaction in ISO 8601 format"),
    ]
    paid_to_issuer: typing_extensions.Annotated[
        PaymentStatus,
        FieldMetadata(alias="paidToIssuer"),
        pydantic.Field(alias="paidToIssuer", description="Payment status to issuer"),
    ]
    commission_earned: typing_extensions.Annotated[
        CommissionEarnedDetails, FieldMetadata(alias="commissionEarned"), pydantic.Field(alias="commissionEarned")
    ]
    payout_timestamp: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="payoutTimestamp"),
        pydantic.Field(
            alias="payoutTimestamp",
            description="Timestamp representing the month when the transaction has been paid out to issuer",
        ),
    ] = None
    components: typing.Optional[OfferComponents] = pydantic.Field(default=None)
    """
    UI component data for the reward, built from the offer state persisted on the matched transaction (e.g. a progress bar for progressive and punch-card offers). Omitted when the reward carries no persisted state.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
