# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .delete_resource_data import DeleteResourceData
    from .delete_resource_response import DeleteResourceResponse
    from .enrolled_reward import EnrolledReward
    from .merchant_network import MerchantNetwork
    from .merchant_network_name import MerchantNetworkName
    from .organization_pagination_metadata import OrganizationPaginationMetadata
_dynamic_imports: typing.Dict[str, str] = {
    "DeleteResourceData": ".delete_resource_data",
    "DeleteResourceResponse": ".delete_resource_response",
    "EnrolledReward": ".enrolled_reward",
    "MerchantNetwork": ".merchant_network",
    "MerchantNetworkName": ".merchant_network_name",
    "OrganizationPaginationMetadata": ".organization_pagination_metadata",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "DeleteResourceData",
    "DeleteResourceResponse",
    "EnrolledReward",
    "MerchantNetwork",
    "MerchantNetworkName",
    "OrganizationPaginationMetadata",
]
