# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...commons.types.empty_object import EmptyObject
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DeleteResourceData(UniversalBaseModel):
    """
    Deleted resource stub
    """

    type: str = pydantic.Field()
    """
    Resource type identifier
    """

    id: str = pydantic.Field()
    """
    ID of the deleted resource
    """

    attributes: EmptyObject

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
