# This file was auto-generated by Fern from our API Definition.

import typing

MerchantNetworkName = typing.Union[
    typing.Literal["EMPYR", "REWARDSNETWORK", "KARD", "COLLINSON", "SEATED", "FRANKI", "LUX"], typing.Any
]
