# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .merchant_network_name import MerchantNetworkName


class MerchantNetwork(UniversalBaseModel):
    """
    Merchant network with priority for an organization
    """

    name: MerchantNetworkName = pydantic.Field()
    """
    Name of the merchant network
    """

    priority: int = pydantic.Field()
    """
    Priority of the merchant network (higher = more preferred)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
