# This file was auto-generated by Fern from our API Definition.

import typing

OrganizationCardNetwork = typing.Union[typing.Literal["VISA", "MASTERCARD", "AMERICAN_EXPRESS", "DISCOVER"], typing.Any]
