# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        ActivateOfferIncludeOption,
        ActivateOfferIncluded,
        ActivateOfferResponse,
        ActivateOfferResponseAttributes,
        ActivateOfferResponseData,
        ActivatePlacementSlotResponse,
        ActivatePlacementSlotResponseAttributes,
        ActivatePlacementSlotResponseData,
        AttributionFilter,
        AttributionState,
        BoostOfferIncludeOption,
        BoostOfferIncluded,
        BoostOfferResponse,
        BoostOfferResponseAttributes,
        BoostOfferResponseData,
        CreateAttributionRequestObject,
        CreateAttributionRequestUnion,
        CreateAttributionRequestUnion_NotificationAttribution,
        CreateAttributionRequestUnion_OfferAttribution,
        CreateAttributionRequestUnion_PlacementSlotAttribution,
        CreateAttributionResponse,
        EventCode,
        NotificationAttributionAttributes,
        NotificationAttributionRequest,
        NotificationMedium,
        OfferAttributionAttributes,
        OfferAttributionRequest,
        OfferMedium,
        PlacementSlotAttributionAttributes,
        PlacementSlotAttributionRequest,
        PlacementSlotMedium,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "ActivateOfferIncludeOption": ".types",
    "ActivateOfferIncluded": ".types",
    "ActivateOfferResponse": ".types",
    "ActivateOfferResponseAttributes": ".types",
    "ActivateOfferResponseData": ".types",
    "ActivatePlacementSlotResponse": ".types",
    "ActivatePlacementSlotResponseAttributes": ".types",
    "ActivatePlacementSlotResponseData": ".types",
    "AttributionFilter": ".types",
    "AttributionState": ".types",
    "BoostOfferIncludeOption": ".types",
    "BoostOfferIncluded": ".types",
    "BoostOfferResponse": ".types",
    "BoostOfferResponseAttributes": ".types",
    "BoostOfferResponseData": ".types",
    "CreateAttributionRequestObject": ".types",
    "CreateAttributionRequestUnion": ".types",
    "CreateAttributionRequestUnion_NotificationAttribution": ".types",
    "CreateAttributionRequestUnion_OfferAttribution": ".types",
    "CreateAttributionRequestUnion_PlacementSlotAttribution": ".types",
    "CreateAttributionResponse": ".types",
    "EventCode": ".types",
    "NotificationAttributionAttributes": ".types",
    "NotificationAttributionRequest": ".types",
    "NotificationMedium": ".types",
    "OfferAttributionAttributes": ".types",
    "OfferAttributionRequest": ".types",
    "OfferMedium": ".types",
    "PlacementSlotAttributionAttributes": ".types",
    "PlacementSlotAttributionRequest": ".types",
    "PlacementSlotMedium": ".types",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ActivateOfferIncludeOption",
    "ActivateOfferIncluded",
    "ActivateOfferResponse",
    "ActivateOfferResponseAttributes",
    "ActivateOfferResponseData",
    "ActivatePlacementSlotResponse",
    "ActivatePlacementSlotResponseAttributes",
    "ActivatePlacementSlotResponseData",
    "AttributionFilter",
    "AttributionState",
    "BoostOfferIncludeOption",
    "BoostOfferIncluded",
    "BoostOfferResponse",
    "BoostOfferResponseAttributes",
    "BoostOfferResponseData",
    "CreateAttributionRequestObject",
    "CreateAttributionRequestUnion",
    "CreateAttributionRequestUnion_NotificationAttribution",
    "CreateAttributionRequestUnion_OfferAttribution",
    "CreateAttributionRequestUnion_PlacementSlotAttribution",
    "CreateAttributionResponse",
    "EventCode",
    "NotificationAttributionAttributes",
    "NotificationAttributionRequest",
    "NotificationMedium",
    "OfferAttributionAttributes",
    "OfferAttributionRequest",
    "OfferMedium",
    "PlacementSlotAttributionAttributes",
    "PlacementSlotAttributionRequest",
    "PlacementSlotMedium",
]
