# This file was auto-generated by Fern from our API Definition.

import typing

from ...commons.types.organization_id import OrganizationId
from ...commons.types.user_id import UserId
from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ..rewards.types.component_type import ComponentType
from .raw_client import AsyncRawAttributionsClient, RawAttributionsClient
from .types.activate_offer_include_option import ActivateOfferIncludeOption
from .types.activate_offer_response import ActivateOfferResponse
from .types.create_attribution_request_union import CreateAttributionRequestUnion
from .types.create_attribution_response import CreateAttributionResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AttributionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAttributionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAttributionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAttributionsClient
        """
        return self._raw_client

    def create(
        self,
        organization_id: OrganizationId,
        user_id: UserId,
        *,
        data: typing.Sequence[CreateAttributionRequestUnion],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateAttributionResponse:
        """
        Call this endpoint to send attribution events made by a single enrolled user for processing. A maximum of 100 events can be included in a single request.

        <b>Required scopes:</b> `attributions:write`

        Parameters
        ----------
        organization_id : OrganizationId

        user_id : UserId

        data : typing.Sequence[CreateAttributionRequestUnion]
            Discriminated union representing the request body for submitting attribution events.
            Use `type` to distinguish between the two:
            - `offerAttribution`: Events related to viewing or interacting with an offer.
            - `notificationAttribution`: Events related to viewing or interacting with a notification.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateAttributionResponse

        Examples
        --------
        import datetime

        from kard import KardApi
        from kard.users.attributions import (
            CreateAttributionRequestUnion_NotificationAttribution,
            CreateAttributionRequestUnion_OfferAttribution,
            NotificationAttributionAttributes,
            OfferAttributionAttributes,
        )

        client = KardApi(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.users.attributions.create(
            organization_id="organization-123",
            user_id="user-123",
            data=[
                CreateAttributionRequestUnion_OfferAttribution(
                    attributes=OfferAttributionAttributes(
                        entity_id="60e4ba1da31c5a22a144c075",
                        event_code="VIEW",
                        medium="SEARCH",
                        event_date=datetime.datetime.fromisoformat(
                            "2025-01-01 00:00:00+00:00",
                        ),
                    ),
                ),
                CreateAttributionRequestUnion_OfferAttribution(
                    attributes=OfferAttributionAttributes(
                        entity_id="60e4ba1da31c5a22a144c077",
                        event_code="IMPRESSION",
                        medium="EMAIL",
                        event_date=datetime.datetime.fromisoformat(
                            "2025-01-01 00:00:00+00:00",
                        ),
                    ),
                ),
                CreateAttributionRequestUnion_NotificationAttribution(
                    attributes=NotificationAttributionAttributes(
                        entity_id="60e4ba1da31c5a22a144c076",
                        event_code="IMPRESSION",
                        medium="PUSH",
                        event_date=datetime.datetime.fromisoformat(
                            "2025-01-01 00:00:00+00:00",
                        ),
                    ),
                ),
            ],
        )
        """
        _response = self._raw_client.create(organization_id, user_id, data=data, request_options=request_options)
        return _response.data

    def activate(
        self,
        organization_id: OrganizationId,
        user_id: UserId,
        offer_id: str,
        *,
        supported_components: typing.Optional[typing.Union[ComponentType, typing.Sequence[ComponentType]]] = None,
        include: typing.Optional[
            typing.Union[ActivateOfferIncludeOption, typing.Sequence[ActivateOfferIncludeOption]]
        ] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ActivateOfferResponse:
        """
        Record when a user activates an offer. Creates an attribution event with eventCode=ACTIVATE and medium=CTA.
        Optionally include the offer data by passing `include=offer`.

        Parameters
        ----------
        organization_id : OrganizationId

        user_id : UserId

        offer_id : str
            The unique identifier of the offer being activated

        supported_components : typing.Optional[typing.Union[ComponentType, typing.Sequence[ComponentType]]]
            UI component types to include in the offer response (when include=offer).

        include : typing.Optional[typing.Union[ActivateOfferIncludeOption, typing.Sequence[ActivateOfferIncludeOption]]]
            Related resources to include in the response. Allowed value is `offer`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ActivateOfferResponse

        Examples
        --------
        from kard import KardApi

        client = KardApi(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.users.attributions.activate(
            organization_id="organization-123",
            user_id="user-123",
            offer_id="offer-456",
        )
        """
        _response = self._raw_client.activate(
            organization_id,
            user_id,
            offer_id,
            supported_components=supported_components,
            include=include,
            request_options=request_options,
        )
        return _response.data


class AsyncAttributionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAttributionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAttributionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAttributionsClient
        """
        return self._raw_client

    async def create(
        self,
        organization_id: OrganizationId,
        user_id: UserId,
        *,
        data: typing.Sequence[CreateAttributionRequestUnion],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateAttributionResponse:
        """
        Call this endpoint to send attribution events made by a single enrolled user for processing. A maximum of 100 events can be included in a single request.

        <b>Required scopes:</b> `attributions:write`

        Parameters
        ----------
        organization_id : OrganizationId

        user_id : UserId

        data : typing.Sequence[CreateAttributionRequestUnion]
            Discriminated union representing the request body for submitting attribution events.
            Use `type` to distinguish between the two:
            - `offerAttribution`: Events related to viewing or interacting with an offer.
            - `notificationAttribution`: Events related to viewing or interacting with a notification.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateAttributionResponse

        Examples
        --------
        import asyncio
        import datetime

        from kard import AsyncKardApi
        from kard.users.attributions import (
            CreateAttributionRequestUnion_NotificationAttribution,
            CreateAttributionRequestUnion_OfferAttribution,
            NotificationAttributionAttributes,
            OfferAttributionAttributes,
        )

        client = AsyncKardApi(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.users.attributions.create(
                organization_id="organization-123",
                user_id="user-123",
                data=[
                    CreateAttributionRequestUnion_OfferAttribution(
                        attributes=OfferAttributionAttributes(
                            entity_id="60e4ba1da31c5a22a144c075",
                            event_code="VIEW",
                            medium="SEARCH",
                            event_date=datetime.datetime.fromisoformat(
                                "2025-01-01 00:00:00+00:00",
                            ),
                        ),
                    ),
                    CreateAttributionRequestUnion_OfferAttribution(
                        attributes=OfferAttributionAttributes(
                            entity_id="60e4ba1da31c5a22a144c077",
                            event_code="IMPRESSION",
                            medium="EMAIL",
                            event_date=datetime.datetime.fromisoformat(
                                "2025-01-01 00:00:00+00:00",
                            ),
                        ),
                    ),
                    CreateAttributionRequestUnion_NotificationAttribution(
                        attributes=NotificationAttributionAttributes(
                            entity_id="60e4ba1da31c5a22a144c076",
                            event_code="IMPRESSION",
                            medium="PUSH",
                            event_date=datetime.datetime.fromisoformat(
                                "2025-01-01 00:00:00+00:00",
                            ),
                        ),
                    ),
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(organization_id, user_id, data=data, request_options=request_options)
        return _response.data

    async def activate(
        self,
        organization_id: OrganizationId,
        user_id: UserId,
        offer_id: str,
        *,
        supported_components: typing.Optional[typing.Union[ComponentType, typing.Sequence[ComponentType]]] = None,
        include: typing.Optional[
            typing.Union[ActivateOfferIncludeOption, typing.Sequence[ActivateOfferIncludeOption]]
        ] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ActivateOfferResponse:
        """
        Record when a user activates an offer. Creates an attribution event with eventCode=ACTIVATE and medium=CTA.
        Optionally include the offer data by passing `include=offer`.

        Parameters
        ----------
        organization_id : OrganizationId

        user_id : UserId

        offer_id : str
            The unique identifier of the offer being activated

        supported_components : typing.Optional[typing.Union[ComponentType, typing.Sequence[ComponentType]]]
            UI component types to include in the offer response (when include=offer).

        include : typing.Optional[typing.Union[ActivateOfferIncludeOption, typing.Sequence[ActivateOfferIncludeOption]]]
            Related resources to include in the response. Allowed value is `offer`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ActivateOfferResponse

        Examples
        --------
        import asyncio

        from kard import AsyncKardApi

        client = AsyncKardApi(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.users.attributions.activate(
                organization_id="organization-123",
                user_id="user-123",
                offer_id="offer-456",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.activate(
            organization_id,
            user_id,
            offer_id,
            supported_components=supported_components,
            include=include,
            request_options=request_options,
        )
        return _response.data
