# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .user_request_data_union import UserRequestDataUnion


class CreateUsersObject(UniversalBaseModel):
    """
    Examples
    --------
    from kard.users import (
        CreateUsersObject,
        UserRequestAttributes,
        UserRequestDataUnion_User,
    )

    CreateUsersObject(
        data=[
            UserRequestDataUnion_User(
                id="1234567890",
                attributes=UserRequestAttributes(
                    zip_code="11238",
                    enrolled_rewards=["CARDLINKED"],
                    email="user@example.com",
                    hashed_email="a94a8fe5ccb19ba61c4c0873d391e987982fbbd3e2d8a5b76e45a1d4c4e2e3a1",
                    phone_number="+14155552671",
                    birth_year="1990",
                    historical_transactions_sent=True,
                ),
            )
        ],
    )
    """

    data: typing.List[UserRequestDataUnion]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
