# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .phone_number_type import PhoneNumberType


class PhoneNumber(UniversalBaseModel):
    number: str = pydantic.Field()
    """
    Phone number in E.164 format
    """

    type: typing.Optional[PhoneNumberType] = pydantic.Field(default=None)
    """
    Kind of phone number. Inferred when omitted.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
