# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .postal_code_type import PostalCodeType


class PostalCode(UniversalBaseModel):
    code: str = pydantic.Field()
    """
    5-digit postal code
    """

    type: typing.Optional[PostalCodeType] = pydantic.Field(default=None)
    """
    Kind of postal code. Inferred when omitted.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
