# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ...commons.types.user_id import UserId
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .update_user_request_attributes import UpdateUserRequestAttributes


class UpdateUserRequestDataUnion_User(UniversalBaseModel):
    type: typing.Literal["user"] = "user"
    id: UserId
    attributes: UpdateUserRequestAttributes

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


UpdateUserRequestDataUnion = UpdateUserRequestDataUnion_User
