# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...commons.types.enrolled_rewards_type import EnrolledRewardsType
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class UpdateUserRequestAttributes(UniversalBaseModel):
    enrolled_rewards: typing_extensions.Annotated[
        typing.List[EnrolledRewardsType],
        FieldMetadata(alias="enrolledRewards"),
        pydantic.Field(
            alias="enrolledRewards",
            description="Rewards programs to enroll the user in. If an empty array is supplied, the user will not be enrolled in any programs.",
        ),
    ]
    zip_code: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="zipCode"),
        pydantic.Field(alias="zipCode", description="Zipcode of user"),
    ] = None
    email: typing.Optional[str] = pydantic.Field(default=None)
    """
    Email address of user
    """

    hashed_email: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="hashedEmail"),
        pydantic.Field(alias="hashedEmail", description="Hashed email address of user (using SHA-256)"),
    ] = None
    phone_number: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="phoneNumber"),
        pydantic.Field(alias="phoneNumber", description="Phone number of user in E.164 format"),
    ] = None
    birth_year: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="birthYear"),
        pydantic.Field(alias="birthYear", description="Birth year of user"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
