# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .content_strategy_attributes import ContentStrategyAttributes
    from .content_strategy_filters import ContentStrategyFilters
    from .content_strategy_list_response import ContentStrategyListResponse
    from .content_strategy_response import ContentStrategyResponse
    from .content_strategy_sort import ContentStrategySort
    from .create_content_strategy_attributes import CreateContentStrategyAttributes
    from .create_content_strategy_request_body import CreateContentStrategyRequestBody
    from .create_content_strategy_request_data import CreateContentStrategyRequestData
    from .offer_features import OfferFeatures
    from .update_content_strategy_attributes import UpdateContentStrategyAttributes
    from .update_content_strategy_request_body import UpdateContentStrategyRequestBody
    from .update_content_strategy_request_data import UpdateContentStrategyRequestData
_dynamic_imports: typing.Dict[str, str] = {
    "ContentStrategyAttributes": ".content_strategy_attributes",
    "ContentStrategyFilters": ".content_strategy_filters",
    "ContentStrategyListResponse": ".content_strategy_list_response",
    "ContentStrategyResponse": ".content_strategy_response",
    "ContentStrategySort": ".content_strategy_sort",
    "CreateContentStrategyAttributes": ".create_content_strategy_attributes",
    "CreateContentStrategyRequestBody": ".create_content_strategy_request_body",
    "CreateContentStrategyRequestData": ".create_content_strategy_request_data",
    "OfferFeatures": ".offer_features",
    "UpdateContentStrategyAttributes": ".update_content_strategy_attributes",
    "UpdateContentStrategyRequestBody": ".update_content_strategy_request_body",
    "UpdateContentStrategyRequestData": ".update_content_strategy_request_data",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ContentStrategyAttributes",
    "ContentStrategyFilters",
    "ContentStrategyListResponse",
    "ContentStrategyResponse",
    "ContentStrategySort",
    "CreateContentStrategyAttributes",
    "CreateContentStrategyRequestBody",
    "CreateContentStrategyRequestData",
    "OfferFeatures",
    "UpdateContentStrategyAttributes",
    "UpdateContentStrategyRequestBody",
    "UpdateContentStrategyRequestData",
]
