# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from .offer_features import OfferFeatures


class ContentStrategyFilters(UniversalBaseModel):
    """
    Filters applied when selecting offers for a content strategy
    """

    categories: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Merchant categories to include
    """

    category_exclusions: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="categoryExclusions"),
        pydantic.Field(alias="categoryExclusions", description="Merchant categories to exclude"),
    ] = None
    merchant_exclusions: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="merchantExclusions"),
        pydantic.Field(alias="merchantExclusions", description="Merchant IDs to exclude"),
    ] = None
    offer_features: typing_extensions.Annotated[
        typing.Optional[typing.List[OfferFeatures]],
        FieldMetadata(alias="offerFeatures"),
        pydantic.Field(alias="offerFeatures", description="Offer features to filter by"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
