# This file was auto-generated by Fern from our API Definition.

import typing

ContentStrategyFilter = typing.Union[
    typing.Literal["NEWLY_LIVE", "EXPIRING_SOON", "HIGHEST_CASHBACK", "PERSONALIZED"], typing.Any
]
