# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .content_strategy_attributes import ContentStrategyAttributes


class ContentStrategyResponse(UniversalBaseModel):
    """
    Content strategy resource response

    Examples
    --------
    import datetime

    from kard.organizations.content_strategies import (
        ContentStrategyAttributes,
        ContentStrategyResponse,
    )

    ContentStrategyResponse(
        id="01961e5a-b74c-7d42-8456-d3a1f2c90e71",
        attributes=ContentStrategyAttributes(
            name="Featured Travel",
            organization_id="org-123",
            filter="HIGHEST_CASHBACK",
            categories=["Travel"],
            category_exclusions=["Gas"],
            merchant_exclusions=["merchant-abc"],
            created_at=datetime.datetime.fromisoformat(
                "2026-04-15 12:00:00+00:00",
            ),
            last_modified=datetime.datetime.fromisoformat(
                "2026-04-15 12:00:00+00:00",
            ),
        ),
    )
    """

    type: typing.Literal["contentStrategy"] = "contentStrategy"
    id: str = pydantic.Field()
    """
    Unique identifier of the content strategy (UUID v7)
    """

    attributes: ContentStrategyAttributes

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
