# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ....commons.types.category_option import CategoryOption
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from .content_strategy_filter import ContentStrategyFilter


class ContentStrategyAttributes(UniversalBaseModel):
    """
    Attributes for a content strategy
    """

    name: str = pydantic.Field()
    """
    Name of the content strategy (unique within an organization)
    """

    organization_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="organizationId"),
        pydantic.Field(alias="organizationId", description="ID of the organization this content strategy belongs to"),
    ]
    filter: typing.Optional[ContentStrategyFilter] = pydantic.Field(default=None)
    """
    Filter applied when selecting offers for the strategy
    """

    categories: typing.List[CategoryOption] = pydantic.Field()
    """
    Merchant categories to include
    """

    category_exclusions: typing_extensions.Annotated[
        typing.List[CategoryOption],
        FieldMetadata(alias="categoryExclusions"),
        pydantic.Field(alias="categoryExclusions", description="Merchant categories to exclude"),
    ]
    merchant_exclusions: typing_extensions.Annotated[
        typing.List[str],
        FieldMetadata(alias="merchantExclusions"),
        pydantic.Field(alias="merchantExclusions", description="Merchant IDs to exclude"),
    ]
    created_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="When the content strategy was created (ISO 8601 UTC)"),
    ]
    last_modified: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="lastModified"),
        pydantic.Field(alias="lastModified", description="When the content strategy was last modified (ISO 8601 UTC)"),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
