# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....commons.types.category_option import CategoryOption
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from .content_strategy_filter import ContentStrategyFilter


class CreateContentStrategyAttributes(UniversalBaseModel):
    """
    Attributes for creating a content strategy

    Examples
    --------
    from kard.organizations.content_strategies import (
        CreateContentStrategyAttributes,
    )

    CreateContentStrategyAttributes(
        name="Featured Travel",
        filters=["HIGHEST_CASHBACK", "NEWLY_LIVE"],
        categories=["Travel"],
        category_exclusions=["Gas"],
        merchant_exclusions=["merchant-abc"],
    )
    """

    name: str = pydantic.Field()
    """
    Name of the content strategy (unique within an organization)
    """

    filters: typing.List[ContentStrategyFilter] = pydantic.Field()
    """
    Filters applied when selecting offers for the strategy
    """

    categories: typing.List[CategoryOption] = pydantic.Field()
    """
    Merchant categories to include
    """

    category_exclusions: typing_extensions.Annotated[
        typing.List[CategoryOption],
        FieldMetadata(alias="categoryExclusions"),
        pydantic.Field(alias="categoryExclusions", description="Merchant categories to exclude"),
    ]
    merchant_exclusions: typing_extensions.Annotated[
        typing.List[str],
        FieldMetadata(alias="merchantExclusions"),
        pydantic.Field(alias="merchantExclusions", description="Merchant IDs to exclude"),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
