# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_content_strategy_request_data import CreateContentStrategyRequestData


class CreateContentStrategyRequestBody(UniversalBaseModel):
    """
    Request body for creating a content strategy

    Examples
    --------
    from kard.organizations.content_strategies import (
        ContentStrategyFilters,
        CreateContentStrategyAttributes,
        CreateContentStrategyRequestBody,
        CreateContentStrategyRequestData,
    )

    CreateContentStrategyRequestBody(
        data=CreateContentStrategyRequestData(
            attributes=CreateContentStrategyAttributes(
                name="Featured Travel",
                sort="HIGHEST_CASHBACK",
                filters=ContentStrategyFilters(
                    offer_features=["INTERACTIVE"],
                ),
                categories=["Travel"],
                category_exclusions=["Gas"],
                merchant_exclusions=["merchant-abc"],
            ),
        ),
    )
    """

    data: CreateContentStrategyRequestData = pydantic.Field()
    """
    Content strategy data for creation
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
