# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .update_content_strategy_attributes import UpdateContentStrategyAttributes


class UpdateContentStrategyRequestData(UniversalBaseModel):
    """
    Content strategy data structure for update
    """

    type: typing.Literal["contentStrategy"] = pydantic.Field(default="contentStrategy")
    """
    Resource type identifier
    """

    attributes: UpdateContentStrategyAttributes = pydantic.Field()
    """
    Content strategy attributes for update
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
