# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        Amount,
        AmountType,
        Asset,
        BatchesMeta,
        BatchesResponseObject,
        CategoryData,
        CategoryFields,
        CategoryIdentifier,
        CategoryIncluded,
        CategoryRelationship,
        CategoryRelationshipObject,
        Commission,
        ComponentType,
        Coordinates,
        EligibilityLocationAddress,
        EligibilityLocationIncluded,
        EligibilityOfferIncluded,
        EligibilityOfferRelationship,
        LocationAttributes,
        LocationData,
        LocationPartnerId,
        LocationPartnerIdType,
        LocationRelationships,
        LocationSortOptions,
        LocationsResponseObject,
        OfferCommonFields,
        OfferDataUnion,
        OfferDataUnion_StandardOffer,
        OfferRelationship,
        OfferSortOptions,
        OffersMeta,
        OffersResponseObject,
        OperationHours,
        OperationPeriod,
        OperationTime,
        PlacementBatchAttributes,
        PlacementBatchData,
        PlacementContentResponse,
        StandardOffer,
        StandardOfferCore,
        StandardOfferFields,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "Amount": ".types",
    "AmountType": ".types",
    "Asset": ".types",
    "BatchesMeta": ".types",
    "BatchesResponseObject": ".types",
    "CategoryData": ".types",
    "CategoryFields": ".types",
    "CategoryIdentifier": ".types",
    "CategoryIncluded": ".types",
    "CategoryRelationship": ".types",
    "CategoryRelationshipObject": ".types",
    "Commission": ".types",
    "ComponentType": ".types",
    "Coordinates": ".types",
    "EligibilityLocationAddress": ".types",
    "EligibilityLocationIncluded": ".types",
    "EligibilityOfferIncluded": ".types",
    "EligibilityOfferRelationship": ".types",
    "LocationAttributes": ".types",
    "LocationData": ".types",
    "LocationPartnerId": ".types",
    "LocationPartnerIdType": ".types",
    "LocationRelationships": ".types",
    "LocationSortOptions": ".types",
    "LocationsResponseObject": ".types",
    "OfferCommonFields": ".types",
    "OfferDataUnion": ".types",
    "OfferDataUnion_StandardOffer": ".types",
    "OfferRelationship": ".types",
    "OfferSortOptions": ".types",
    "OffersMeta": ".types",
    "OffersResponseObject": ".types",
    "OperationHours": ".types",
    "OperationPeriod": ".types",
    "OperationTime": ".types",
    "PlacementBatchAttributes": ".types",
    "PlacementBatchData": ".types",
    "PlacementContentResponse": ".types",
    "StandardOffer": ".types",
    "StandardOfferCore": ".types",
    "StandardOfferFields": ".types",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "Amount",
    "AmountType",
    "Asset",
    "BatchesMeta",
    "BatchesResponseObject",
    "CategoryData",
    "CategoryFields",
    "CategoryIdentifier",
    "CategoryIncluded",
    "CategoryRelationship",
    "CategoryRelationshipObject",
    "Commission",
    "ComponentType",
    "Coordinates",
    "EligibilityLocationAddress",
    "EligibilityLocationIncluded",
    "EligibilityOfferIncluded",
    "EligibilityOfferRelationship",
    "LocationAttributes",
    "LocationData",
    "LocationPartnerId",
    "LocationPartnerIdType",
    "LocationRelationships",
    "LocationSortOptions",
    "LocationsResponseObject",
    "OfferCommonFields",
    "OfferDataUnion",
    "OfferDataUnion_StandardOffer",
    "OfferRelationship",
    "OfferSortOptions",
    "OffersMeta",
    "OffersResponseObject",
    "OperationHours",
    "OperationPeriod",
    "OperationTime",
    "PlacementBatchAttributes",
    "PlacementBatchData",
    "PlacementContentResponse",
    "StandardOffer",
    "StandardOfferCore",
    "StandardOfferFields",
]
