# This file was auto-generated by Fern from our API Definition.

import typing

from ...commons.types.category_option import CategoryOption
from ...commons.types.organization_id import OrganizationId
from ...commons.types.purchase_channel import PurchaseChannel
from ...commons.types.state import State
from ...commons.types.user_id import UserId
from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from .raw_client import AsyncRawRewardsClient, RawRewardsClient
from .types.batches_response_object import BatchesResponseObject
from .types.component_type import ComponentType
from .types.location_sort_options import LocationSortOptions
from .types.locations_response_object import LocationsResponseObject
from .types.offer_sort_options import OfferSortOptions
from .types.offers_response_object import OffersResponseObject
from .types.placement_content_response import PlacementContentResponse


class RewardsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawRewardsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawRewardsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawRewardsClient
        """
        return self._raw_client

    def offers(
        self,
        organization_id: OrganizationId,
        user_id: UserId,
        *,
        page_size: typing.Optional[int] = None,
        page_after: typing.Optional[str] = None,
        page_before: typing.Optional[str] = None,
        filter_search: typing.Optional[str] = None,
        filter_purchase_channel: typing.Optional[typing.Sequence[PurchaseChannel]] = None,
        filter_category: typing.Optional[CategoryOption] = None,
        filter_is_targeted: typing.Optional[bool] = None,
        sort: typing.Optional[typing.Union[OfferSortOptions, typing.Sequence[OfferSortOptions]]] = None,
        include: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        supported_components: typing.Optional[typing.Union[ComponentType, typing.Sequence[ComponentType]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OffersResponseObject:
        """
        Retrieve national brand offers that a specified user is eligible for. Call this endpoint to build out your
        [targeted offers UX experience](/2024-10-01/api/getting-started#b-discover-a-lapsed-customer-clo). Local offers details
        can be found by calling the [Get Eligible Locations](/2024-10-01/api/rewards/locations).<br/>
        <b>Required scopes:</b> `rewards:read`

        Parameters
        ----------
        organization_id : OrganizationId

        user_id : UserId

        page_size : typing.Optional[int]

        page_after : typing.Optional[str]

        page_before : typing.Optional[str]

        filter_search : typing.Optional[str]
            Case-insensitive search string to filter offers by merchant name

        filter_purchase_channel : typing.Optional[typing.Sequence[PurchaseChannel]]

        filter_category : typing.Optional[CategoryOption]

        filter_is_targeted : typing.Optional[bool]

        sort : typing.Optional[typing.Union[OfferSortOptions, typing.Sequence[OfferSortOptions]]]
            If provided, response will be sorted by the specified fields

        include : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            CSV list of included resources in the response (e.g "categories"). Allowed value is `categories`.

        supported_components : typing.Optional[typing.Union[ComponentType, typing.Sequence[ComponentType]]]
            UI component types to include in the response.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OffersResponseObject

        Examples
        --------
        from kard import KardApi

        client = KardApi(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.users.rewards.offers(
            organization_id="organization-123",
            user_id="user-123",
            page_size=1,
            filter_is_targeted=True,
            sort="-startDate",
        )
        """
        _response = self._raw_client.offers(
            organization_id,
            user_id,
            page_size=page_size,
            page_after=page_after,
            page_before=page_before,
            filter_search=filter_search,
            filter_purchase_channel=filter_purchase_channel,
            filter_category=filter_category,
            filter_is_targeted=filter_is_targeted,
            sort=sort,
            include=include,
            supported_components=supported_components,
            request_options=request_options,
        )
        return _response.data

    def placement_offers(
        self,
        organization_id: OrganizationId,
        user_id: UserId,
        placement_id: str,
        *,
        filter_search: typing.Optional[str] = None,
        filter_purchase_channel: typing.Optional[typing.Sequence[PurchaseChannel]] = None,
        filter_category: typing.Optional[CategoryOption] = None,
        filter_is_targeted: typing.Optional[bool] = None,
        include: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        supported_components: typing.Optional[typing.Union[ComponentType, typing.Sequence[ComponentType]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OffersResponseObject:
        """
        Retrieve offers for a placement slot. Returns offers sorted by highest cash back,
        limited by the placement's available slots.<br/>
        <b>Required scopes:</b> `rewards:read`

        Parameters
        ----------
        organization_id : OrganizationId

        user_id : UserId

        placement_id : str

        filter_search : typing.Optional[str]
            Case-insensitive search string to filter offers by merchant name

        filter_purchase_channel : typing.Optional[typing.Sequence[PurchaseChannel]]

        filter_category : typing.Optional[CategoryOption]

        filter_is_targeted : typing.Optional[bool]

        include : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            CSV list of included resources in the response (e.g "categories"). Allowed value is `categories`.

        supported_components : typing.Optional[typing.Union[ComponentType, typing.Sequence[ComponentType]]]
            UI component types to include in the response.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OffersResponseObject

        Examples
        --------
        from kard import KardApi

        client = KardApi(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.users.rewards.placement_offers(
            organization_id="organizationId",
            user_id="userId",
            placement_id="placementId",
        )
        """
        _response = self._raw_client.placement_offers(
            organization_id,
            user_id,
            placement_id,
            filter_search=filter_search,
            filter_purchase_channel=filter_purchase_channel,
            filter_category=filter_category,
            filter_is_targeted=filter_is_targeted,
            include=include,
            supported_components=supported_components,
            request_options=request_options,
        )
        return _response.data

    def placement_batches(
        self,
        organization_id: OrganizationId,
        user_id: UserId,
        placement_id: str,
        *,
        supported_components: typing.Optional[typing.Union[ComponentType, typing.Sequence[ComponentType]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BatchesResponseObject:
        """
        Retrieve batches for a batch-activation or group placement. Returns each
        slot in slot order with its current offer set, alias, and freshness fields
        (`isActive`, `lastActivatedAt`, `expiresAt`). Applies the same per-user
        eligibility and per-slot content-strategy filter as Get Offers By
        Placement, independently per slot. For a batch-activation placement, a
        slot only flips to `isActive: false` when its refresh interval has elapsed
        AND its post-eligibility `offers[]` is non-empty; otherwise the slot is
        still returned and stays active so the partner UI does not promote
        "refresh" with nothing to show. For a group placement, slots are always
        active and each slot returns its offers regardless of activation state,
        hiding only offers that require activation (`requiredInBatch`) and have
        no activation record.<br/>
        <b>Required scopes:</b> `rewards:read`

        Parameters
        ----------
        organization_id : OrganizationId

        user_id : UserId

        placement_id : str

        supported_components : typing.Optional[typing.Union[ComponentType, typing.Sequence[ComponentType]]]
            UI component types to include in the response.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BatchesResponseObject

        Examples
        --------
        from kard import KardApi

        client = KardApi(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.users.rewards.placement_batches(
            organization_id="organizationId",
            user_id="userId",
            placement_id="placementId",
        )
        """
        _response = self._raw_client.placement_batches(
            organization_id,
            user_id,
            placement_id,
            supported_components=supported_components,
            request_options=request_options,
        )
        return _response.data

    def placement_content(
        self,
        organization_id: OrganizationId,
        user_id: UserId,
        placement_id: str,
        *,
        include: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        supported_components: typing.Optional[typing.Union[ComponentType, typing.Sequence[ComponentType]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PlacementContentResponse:
        """
        Retrieve the content for a placement. The placement type is resolved
        server-side so callers no longer pick an endpoint by placement type.
        Returns a JSON:API document whose `data` resources are self-describing
        by `type`: a standard placement returns `standardOffer` resources (the
        same payload as Get Offers By Placement — with `links`, optional
        `included` categories, and `meta`); a batch-activation or group
        placement returns `placementBatch` slot resources (the same payload as
        Get Batches By Placement). Distinguish the two by each resource's
        `type`. Email and push-notification placements are not servable through
        this endpoint and respond with a `400`.<br/>
        <b>Required scopes:</b> `rewards:read`

        Parameters
        ----------
        organization_id : OrganizationId

        user_id : UserId

        placement_id : str

        include : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            CSV list of included resources in the response (e.g "categories"). Allowed value is `categories`. Only applies to standard placements (those returning `standardOffer` resources).

        supported_components : typing.Optional[typing.Union[ComponentType, typing.Sequence[ComponentType]]]
            UI component types to include in the response.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PlacementContentResponse

        Examples
        --------
        from kard import KardApi

        client = KardApi(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.users.rewards.placement_content(
            organization_id="organization-123",
            user_id="user-123",
            placement_id="placement-homepage-banner",
            include="categories",
        )
        """
        _response = self._raw_client.placement_content(
            organization_id,
            user_id,
            placement_id,
            include=include,
            supported_components=supported_components,
            request_options=request_options,
        )
        return _response.data

    def locations(
        self,
        organization_id: OrganizationId,
        user_id: UserId,
        *,
        page_size: typing.Optional[int] = None,
        page_after: typing.Optional[str] = None,
        page_before: typing.Optional[str] = None,
        filter_name: typing.Optional[str] = None,
        filter_city: typing.Optional[str] = None,
        filter_zip_code: typing.Optional[str] = None,
        filter_state: typing.Optional[State] = None,
        filter_category: typing.Optional[CategoryOption] = None,
        filter_longitude: typing.Optional[float] = None,
        filter_latitude: typing.Optional[float] = None,
        filter_radius: typing.Optional[int] = None,
        sort: typing.Optional[typing.Union[LocationSortOptions, typing.Sequence[LocationSortOptions]]] = None,
        include: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        supported_components: typing.Optional[typing.Union[ComponentType, typing.Sequence[ComponentType]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> LocationsResponseObject:
        """
        Retrieve national and local geographic locations that a specified user has eligible in-store offers at. Use this endpoint to build
        out your [map-specific UX experiences](/2024-10-01/api/getting-started#c-discover-clos-near-you-map-view). Please note
        that Longitude and Latitude fields are prioritized over State, City and Zipcode and are the recommended search
        pattern.<br/>
        <br/>
        <b>Required scopes:</b> `rewards:read`

        Parameters
        ----------
        organization_id : OrganizationId

        user_id : UserId

        page_size : typing.Optional[int]

        page_after : typing.Optional[str]

        page_before : typing.Optional[str]

        filter_name : typing.Optional[str]

        filter_city : typing.Optional[str]

        filter_zip_code : typing.Optional[str]

        filter_state : typing.Optional[State]

        filter_category : typing.Optional[CategoryOption]

        filter_longitude : typing.Optional[float]

        filter_latitude : typing.Optional[float]

        filter_radius : typing.Optional[int]

        sort : typing.Optional[typing.Union[LocationSortOptions, typing.Sequence[LocationSortOptions]]]
            If provided, response will be sorted by the specified fields

        include : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            CSV list of included resources in the response (e.g "offers,categories"). Allowed values are `offers` and `categories`.

        supported_components : typing.Optional[typing.Union[ComponentType, typing.Sequence[ComponentType]]]
            UI component types to include in included offers.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LocationsResponseObject

        Examples
        --------
        from kard import KardApi

        client = KardApi(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.users.rewards.locations(
            organization_id="organization-123",
            user_id="user-123",
            page_size=1,
            filter_latitude=39.9419429,
            filter_longitude=-75.1446869,
            filter_radius=10,
            include="offers,categories",
        )
        """
        _response = self._raw_client.locations(
            organization_id,
            user_id,
            page_size=page_size,
            page_after=page_after,
            page_before=page_before,
            filter_name=filter_name,
            filter_city=filter_city,
            filter_zip_code=filter_zip_code,
            filter_state=filter_state,
            filter_category=filter_category,
            filter_longitude=filter_longitude,
            filter_latitude=filter_latitude,
            filter_radius=filter_radius,
            sort=sort,
            include=include,
            supported_components=supported_components,
            request_options=request_options,
        )
        return _response.data


class AsyncRewardsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawRewardsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawRewardsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawRewardsClient
        """
        return self._raw_client

    async def offers(
        self,
        organization_id: OrganizationId,
        user_id: UserId,
        *,
        page_size: typing.Optional[int] = None,
        page_after: typing.Optional[str] = None,
        page_before: typing.Optional[str] = None,
        filter_search: typing.Optional[str] = None,
        filter_purchase_channel: typing.Optional[typing.Sequence[PurchaseChannel]] = None,
        filter_category: typing.Optional[CategoryOption] = None,
        filter_is_targeted: typing.Optional[bool] = None,
        sort: typing.Optional[typing.Union[OfferSortOptions, typing.Sequence[OfferSortOptions]]] = None,
        include: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        supported_components: typing.Optional[typing.Union[ComponentType, typing.Sequence[ComponentType]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OffersResponseObject:
        """
        Retrieve national brand offers that a specified user is eligible for. Call this endpoint to build out your
        [targeted offers UX experience](/2024-10-01/api/getting-started#b-discover-a-lapsed-customer-clo). Local offers details
        can be found by calling the [Get Eligible Locations](/2024-10-01/api/rewards/locations).<br/>
        <b>Required scopes:</b> `rewards:read`

        Parameters
        ----------
        organization_id : OrganizationId

        user_id : UserId

        page_size : typing.Optional[int]

        page_after : typing.Optional[str]

        page_before : typing.Optional[str]

        filter_search : typing.Optional[str]
            Case-insensitive search string to filter offers by merchant name

        filter_purchase_channel : typing.Optional[typing.Sequence[PurchaseChannel]]

        filter_category : typing.Optional[CategoryOption]

        filter_is_targeted : typing.Optional[bool]

        sort : typing.Optional[typing.Union[OfferSortOptions, typing.Sequence[OfferSortOptions]]]
            If provided, response will be sorted by the specified fields

        include : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            CSV list of included resources in the response (e.g "categories"). Allowed value is `categories`.

        supported_components : typing.Optional[typing.Union[ComponentType, typing.Sequence[ComponentType]]]
            UI component types to include in the response.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OffersResponseObject

        Examples
        --------
        import asyncio

        from kard import AsyncKardApi

        client = AsyncKardApi(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.users.rewards.offers(
                organization_id="organization-123",
                user_id="user-123",
                page_size=1,
                filter_is_targeted=True,
                sort="-startDate",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.offers(
            organization_id,
            user_id,
            page_size=page_size,
            page_after=page_after,
            page_before=page_before,
            filter_search=filter_search,
            filter_purchase_channel=filter_purchase_channel,
            filter_category=filter_category,
            filter_is_targeted=filter_is_targeted,
            sort=sort,
            include=include,
            supported_components=supported_components,
            request_options=request_options,
        )
        return _response.data

    async def placement_offers(
        self,
        organization_id: OrganizationId,
        user_id: UserId,
        placement_id: str,
        *,
        filter_search: typing.Optional[str] = None,
        filter_purchase_channel: typing.Optional[typing.Sequence[PurchaseChannel]] = None,
        filter_category: typing.Optional[CategoryOption] = None,
        filter_is_targeted: typing.Optional[bool] = None,
        include: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        supported_components: typing.Optional[typing.Union[ComponentType, typing.Sequence[ComponentType]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OffersResponseObject:
        """
        Retrieve offers for a placement slot. Returns offers sorted by highest cash back,
        limited by the placement's available slots.<br/>
        <b>Required scopes:</b> `rewards:read`

        Parameters
        ----------
        organization_id : OrganizationId

        user_id : UserId

        placement_id : str

        filter_search : typing.Optional[str]
            Case-insensitive search string to filter offers by merchant name

        filter_purchase_channel : typing.Optional[typing.Sequence[PurchaseChannel]]

        filter_category : typing.Optional[CategoryOption]

        filter_is_targeted : typing.Optional[bool]

        include : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            CSV list of included resources in the response (e.g "categories"). Allowed value is `categories`.

        supported_components : typing.Optional[typing.Union[ComponentType, typing.Sequence[ComponentType]]]
            UI component types to include in the response.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OffersResponseObject

        Examples
        --------
        import asyncio

        from kard import AsyncKardApi

        client = AsyncKardApi(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.users.rewards.placement_offers(
                organization_id="organizationId",
                user_id="userId",
                placement_id="placementId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.placement_offers(
            organization_id,
            user_id,
            placement_id,
            filter_search=filter_search,
            filter_purchase_channel=filter_purchase_channel,
            filter_category=filter_category,
            filter_is_targeted=filter_is_targeted,
            include=include,
            supported_components=supported_components,
            request_options=request_options,
        )
        return _response.data

    async def placement_batches(
        self,
        organization_id: OrganizationId,
        user_id: UserId,
        placement_id: str,
        *,
        supported_components: typing.Optional[typing.Union[ComponentType, typing.Sequence[ComponentType]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BatchesResponseObject:
        """
        Retrieve batches for a batch-activation or group placement. Returns each
        slot in slot order with its current offer set, alias, and freshness fields
        (`isActive`, `lastActivatedAt`, `expiresAt`). Applies the same per-user
        eligibility and per-slot content-strategy filter as Get Offers By
        Placement, independently per slot. For a batch-activation placement, a
        slot only flips to `isActive: false` when its refresh interval has elapsed
        AND its post-eligibility `offers[]` is non-empty; otherwise the slot is
        still returned and stays active so the partner UI does not promote
        "refresh" with nothing to show. For a group placement, slots are always
        active and each slot returns its offers regardless of activation state,
        hiding only offers that require activation (`requiredInBatch`) and have
        no activation record.<br/>
        <b>Required scopes:</b> `rewards:read`

        Parameters
        ----------
        organization_id : OrganizationId

        user_id : UserId

        placement_id : str

        supported_components : typing.Optional[typing.Union[ComponentType, typing.Sequence[ComponentType]]]
            UI component types to include in the response.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BatchesResponseObject

        Examples
        --------
        import asyncio

        from kard import AsyncKardApi

        client = AsyncKardApi(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.users.rewards.placement_batches(
                organization_id="organizationId",
                user_id="userId",
                placement_id="placementId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.placement_batches(
            organization_id,
            user_id,
            placement_id,
            supported_components=supported_components,
            request_options=request_options,
        )
        return _response.data

    async def placement_content(
        self,
        organization_id: OrganizationId,
        user_id: UserId,
        placement_id: str,
        *,
        include: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        supported_components: typing.Optional[typing.Union[ComponentType, typing.Sequence[ComponentType]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PlacementContentResponse:
        """
        Retrieve the content for a placement. The placement type is resolved
        server-side so callers no longer pick an endpoint by placement type.
        Returns a JSON:API document whose `data` resources are self-describing
        by `type`: a standard placement returns `standardOffer` resources (the
        same payload as Get Offers By Placement — with `links`, optional
        `included` categories, and `meta`); a batch-activation or group
        placement returns `placementBatch` slot resources (the same payload as
        Get Batches By Placement). Distinguish the two by each resource's
        `type`. Email and push-notification placements are not servable through
        this endpoint and respond with a `400`.<br/>
        <b>Required scopes:</b> `rewards:read`

        Parameters
        ----------
        organization_id : OrganizationId

        user_id : UserId

        placement_id : str

        include : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            CSV list of included resources in the response (e.g "categories"). Allowed value is `categories`. Only applies to standard placements (those returning `standardOffer` resources).

        supported_components : typing.Optional[typing.Union[ComponentType, typing.Sequence[ComponentType]]]
            UI component types to include in the response.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PlacementContentResponse

        Examples
        --------
        import asyncio

        from kard import AsyncKardApi

        client = AsyncKardApi(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.users.rewards.placement_content(
                organization_id="organization-123",
                user_id="user-123",
                placement_id="placement-homepage-banner",
                include="categories",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.placement_content(
            organization_id,
            user_id,
            placement_id,
            include=include,
            supported_components=supported_components,
            request_options=request_options,
        )
        return _response.data

    async def locations(
        self,
        organization_id: OrganizationId,
        user_id: UserId,
        *,
        page_size: typing.Optional[int] = None,
        page_after: typing.Optional[str] = None,
        page_before: typing.Optional[str] = None,
        filter_name: typing.Optional[str] = None,
        filter_city: typing.Optional[str] = None,
        filter_zip_code: typing.Optional[str] = None,
        filter_state: typing.Optional[State] = None,
        filter_category: typing.Optional[CategoryOption] = None,
        filter_longitude: typing.Optional[float] = None,
        filter_latitude: typing.Optional[float] = None,
        filter_radius: typing.Optional[int] = None,
        sort: typing.Optional[typing.Union[LocationSortOptions, typing.Sequence[LocationSortOptions]]] = None,
        include: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        supported_components: typing.Optional[typing.Union[ComponentType, typing.Sequence[ComponentType]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> LocationsResponseObject:
        """
        Retrieve national and local geographic locations that a specified user has eligible in-store offers at. Use this endpoint to build
        out your [map-specific UX experiences](/2024-10-01/api/getting-started#c-discover-clos-near-you-map-view). Please note
        that Longitude and Latitude fields are prioritized over State, City and Zipcode and are the recommended search
        pattern.<br/>
        <br/>
        <b>Required scopes:</b> `rewards:read`

        Parameters
        ----------
        organization_id : OrganizationId

        user_id : UserId

        page_size : typing.Optional[int]

        page_after : typing.Optional[str]

        page_before : typing.Optional[str]

        filter_name : typing.Optional[str]

        filter_city : typing.Optional[str]

        filter_zip_code : typing.Optional[str]

        filter_state : typing.Optional[State]

        filter_category : typing.Optional[CategoryOption]

        filter_longitude : typing.Optional[float]

        filter_latitude : typing.Optional[float]

        filter_radius : typing.Optional[int]

        sort : typing.Optional[typing.Union[LocationSortOptions, typing.Sequence[LocationSortOptions]]]
            If provided, response will be sorted by the specified fields

        include : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            CSV list of included resources in the response (e.g "offers,categories"). Allowed values are `offers` and `categories`.

        supported_components : typing.Optional[typing.Union[ComponentType, typing.Sequence[ComponentType]]]
            UI component types to include in included offers.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LocationsResponseObject

        Examples
        --------
        import asyncio

        from kard import AsyncKardApi

        client = AsyncKardApi(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.users.rewards.locations(
                organization_id="organization-123",
                user_id="user-123",
                page_size=1,
                filter_latitude=39.9419429,
                filter_longitude=-75.1446869,
                filter_radius=10,
                include="offers,categories",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.locations(
            organization_id,
            user_id,
            page_size=page_size,
            page_after=page_after,
            page_before=page_before,
            filter_name=filter_name,
            filter_city=filter_city,
            filter_zip_code=filter_zip_code,
            filter_state=filter_state,
            filter_category=filter_category,
            filter_longitude=filter_longitude,
            filter_latitude=filter_latitude,
            filter_radius=filter_radius,
            sort=sort,
            include=include,
            supported_components=supported_components,
            request_options=request_options,
        )
        return _response.data
