# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        ButtonStyle,
        CardNetwork,
        CategoryOption,
        CommissionType,
        CommissionValue,
        CommissionValueType,
        CtaAction,
        CtaComponent,
        CuisineOption,
        EmptyObject,
        EnrolledRewardsType,
        ErrorObject,
        ErrorResponse,
        ErrorSource,
        Job,
        JobResponse,
        JobStatus,
        Links,
        LogoFlare,
        LogoFlareBadge,
        LogoFlareBadgePosition,
        LogoFlareBorderColor,
        MongoId,
        NotificationType,
        OfferComponents,
        OrganizationId,
        ProgressBar,
        ProgressBarLabelPair,
        ProgressBarLabels,
        ProgressBarSegment,
        ProgressBarSegmentLabel,
        ProgressBarSegmentPosition,
        ProgressBarSegmentProgress,
        ProgressBarSegmentSelection,
        ProgressBarSegmentSeparator,
        ProgressBarSegments,
        PurchaseChannel,
        RejectedReason,
        RelationshipData,
        RelationshipMultiple,
        RelationshipSingle,
        ResourceType,
        State,
        SubscriptionId,
        UserId,
    )
    from .errors import (
        ConflictError,
        DoesNotExistError,
        ForbiddenError,
        InternalServerError,
        InvalidRequest,
        UnauthorizedError,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "ButtonStyle": ".types",
    "CardNetwork": ".types",
    "CategoryOption": ".types",
    "CommissionType": ".types",
    "CommissionValue": ".types",
    "CommissionValueType": ".types",
    "ConflictError": ".errors",
    "CtaAction": ".types",
    "CtaComponent": ".types",
    "CuisineOption": ".types",
    "DoesNotExistError": ".errors",
    "EmptyObject": ".types",
    "EnrolledRewardsType": ".types",
    "ErrorObject": ".types",
    "ErrorResponse": ".types",
    "ErrorSource": ".types",
    "ForbiddenError": ".errors",
    "InternalServerError": ".errors",
    "InvalidRequest": ".errors",
    "Job": ".types",
    "JobResponse": ".types",
    "JobStatus": ".types",
    "Links": ".types",
    "LogoFlare": ".types",
    "LogoFlareBadge": ".types",
    "LogoFlareBadgePosition": ".types",
    "LogoFlareBorderColor": ".types",
    "MongoId": ".types",
    "NotificationType": ".types",
    "OfferComponents": ".types",
    "OrganizationId": ".types",
    "ProgressBar": ".types",
    "ProgressBarLabelPair": ".types",
    "ProgressBarLabels": ".types",
    "ProgressBarSegment": ".types",
    "ProgressBarSegmentLabel": ".types",
    "ProgressBarSegmentPosition": ".types",
    "ProgressBarSegmentProgress": ".types",
    "ProgressBarSegmentSelection": ".types",
    "ProgressBarSegmentSeparator": ".types",
    "ProgressBarSegments": ".types",
    "PurchaseChannel": ".types",
    "RejectedReason": ".types",
    "RelationshipData": ".types",
    "RelationshipMultiple": ".types",
    "RelationshipSingle": ".types",
    "ResourceType": ".types",
    "State": ".types",
    "SubscriptionId": ".types",
    "UnauthorizedError": ".errors",
    "UserId": ".types",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ButtonStyle",
    "CardNetwork",
    "CategoryOption",
    "CommissionType",
    "CommissionValue",
    "CommissionValueType",
    "ConflictError",
    "CtaAction",
    "CtaComponent",
    "CuisineOption",
    "DoesNotExistError",
    "EmptyObject",
    "EnrolledRewardsType",
    "ErrorObject",
    "ErrorResponse",
    "ErrorSource",
    "ForbiddenError",
    "InternalServerError",
    "InvalidRequest",
    "Job",
    "JobResponse",
    "JobStatus",
    "Links",
    "LogoFlare",
    "LogoFlareBadge",
    "LogoFlareBadgePosition",
    "LogoFlareBorderColor",
    "MongoId",
    "NotificationType",
    "OfferComponents",
    "OrganizationId",
    "ProgressBar",
    "ProgressBarLabelPair",
    "ProgressBarLabels",
    "ProgressBarSegment",
    "ProgressBarSegmentLabel",
    "ProgressBarSegmentPosition",
    "ProgressBarSegmentProgress",
    "ProgressBarSegmentSelection",
    "ProgressBarSegmentSeparator",
    "ProgressBarSegments",
    "PurchaseChannel",
    "RejectedReason",
    "RelationshipData",
    "RelationshipMultiple",
    "RelationshipSingle",
    "ResourceType",
    "State",
    "SubscriptionId",
    "UnauthorizedError",
    "UserId",
]
