# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...internal_organizations.types.delete_resource_response import DeleteResourceResponse
from ..types.external_organization_response import ExternalOrganizationResponse
from .raw_client import AsyncRawChildrenClient, RawChildrenClient
from .types.child_organization_list_response import ChildOrganizationListResponse
from .types.create_child_request_data import CreateChildRequestData
from .types.update_child_request_data import UpdateChildRequestData

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ChildrenClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawChildrenClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawChildrenClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawChildrenClient
        """
        return self._raw_client

    def list(
        self,
        organization_id: str,
        *,
        page_after: typing.Optional[str] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ChildOrganizationListResponse:
        """
        List child organizations belonging to the authenticated issuer

        Parameters
        ----------
        organization_id : str
            Unique identifier of the parent organization

        page_after : typing.Optional[str]
            Cursor value for the next page of results

        page_size : typing.Optional[int]
            Maximum number of records to return [1 - 200] (default = 200)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ChildOrganizationListResponse
            Paginated list of child organizations

        Examples
        --------
        from kard import KardApi

        client = KardApi(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.organizations.children.list(
            organization_id="organizationId",
        )
        """
        _response = self._raw_client.list(
            organization_id, page_after=page_after, page_size=page_size, request_options=request_options
        )
        return _response.data

    def create(
        self,
        organization_id: str,
        *,
        data: CreateChildRequestData,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ExternalOrganizationResponse:
        """
        Create a child organization by cloning the parent and overriding specified fields. An 8-digit numeric ID is generated automatically. The name is required, must be uppercase, and must not contain spaces.

        Parameters
        ----------
        organization_id : str
            Unique identifier of the parent organization

        data : CreateChildRequestData
            Child organization data for creation

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExternalOrganizationResponse
            Created child organization resource

        Examples
        --------
        from kard import KardApi
        from kard.organizations.children import (
            CreateChildAttributes,
            CreateChildRequestData,
        )

        client = KardApi(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.organizations.children.create(
            organization_id="organizationId",
            data=CreateChildRequestData(
                attributes=CreateChildAttributes(
                    name="name",
                ),
            ),
        )
        """
        _response = self._raw_client.create(organization_id, data=data, request_options=request_options)
        return _response.data

    def get(
        self, organization_id: str, child_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ExternalOrganizationResponse:
        """
        Retrieve a specific child organization

        Parameters
        ----------
        organization_id : str
            Unique identifier of the parent organization

        child_id : str
            Unique identifier of the child organization

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExternalOrganizationResponse
            Child organization resource

        Examples
        --------
        from kard import KardApi

        client = KardApi(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.organizations.children.get(
            organization_id="organizationId",
            child_id="childId",
        )
        """
        _response = self._raw_client.get(organization_id, child_id, request_options=request_options)
        return _response.data

    def update(
        self,
        organization_id: str,
        child_id: str,
        *,
        data: UpdateChildRequestData,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ExternalOrganizationResponse:
        """
        Update a child organization. Only the name can be changed.

        Parameters
        ----------
        organization_id : str
            Unique identifier of the parent organization

        child_id : str
            Unique identifier of the child organization

        data : UpdateChildRequestData
            Child organization data for update

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExternalOrganizationResponse
            Updated child organization resource

        Examples
        --------
        from kard import KardApi
        from kard.organizations.children import (
            UpdateChildAttributes,
            UpdateChildRequestData,
        )

        client = KardApi(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.organizations.children.update(
            organization_id="organizationId",
            child_id="childId",
            data=UpdateChildRequestData(
                attributes=UpdateChildAttributes(),
            ),
        )
        """
        _response = self._raw_client.update(organization_id, child_id, data=data, request_options=request_options)
        return _response.data

    def delete(
        self, organization_id: str, child_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DeleteResourceResponse:
        """
        Delete a child organization

        Parameters
        ----------
        organization_id : str
            Unique identifier of the parent organization

        child_id : str
            Unique identifier of the child organization

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteResourceResponse

        Examples
        --------
        from kard import KardApi

        client = KardApi(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.organizations.children.delete(
            organization_id="organizationId",
            child_id="childId",
        )
        """
        _response = self._raw_client.delete(organization_id, child_id, request_options=request_options)
        return _response.data


class AsyncChildrenClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawChildrenClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawChildrenClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawChildrenClient
        """
        return self._raw_client

    async def list(
        self,
        organization_id: str,
        *,
        page_after: typing.Optional[str] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ChildOrganizationListResponse:
        """
        List child organizations belonging to the authenticated issuer

        Parameters
        ----------
        organization_id : str
            Unique identifier of the parent organization

        page_after : typing.Optional[str]
            Cursor value for the next page of results

        page_size : typing.Optional[int]
            Maximum number of records to return [1 - 200] (default = 200)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ChildOrganizationListResponse
            Paginated list of child organizations

        Examples
        --------
        import asyncio

        from kard import AsyncKardApi

        client = AsyncKardApi(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.organizations.children.list(
                organization_id="organizationId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            organization_id, page_after=page_after, page_size=page_size, request_options=request_options
        )
        return _response.data

    async def create(
        self,
        organization_id: str,
        *,
        data: CreateChildRequestData,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ExternalOrganizationResponse:
        """
        Create a child organization by cloning the parent and overriding specified fields. An 8-digit numeric ID is generated automatically. The name is required, must be uppercase, and must not contain spaces.

        Parameters
        ----------
        organization_id : str
            Unique identifier of the parent organization

        data : CreateChildRequestData
            Child organization data for creation

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExternalOrganizationResponse
            Created child organization resource

        Examples
        --------
        import asyncio

        from kard import AsyncKardApi
        from kard.organizations.children import (
            CreateChildAttributes,
            CreateChildRequestData,
        )

        client = AsyncKardApi(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.organizations.children.create(
                organization_id="organizationId",
                data=CreateChildRequestData(
                    attributes=CreateChildAttributes(
                        name="name",
                    ),
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(organization_id, data=data, request_options=request_options)
        return _response.data

    async def get(
        self, organization_id: str, child_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ExternalOrganizationResponse:
        """
        Retrieve a specific child organization

        Parameters
        ----------
        organization_id : str
            Unique identifier of the parent organization

        child_id : str
            Unique identifier of the child organization

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExternalOrganizationResponse
            Child organization resource

        Examples
        --------
        import asyncio

        from kard import AsyncKardApi

        client = AsyncKardApi(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.organizations.children.get(
                organization_id="organizationId",
                child_id="childId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(organization_id, child_id, request_options=request_options)
        return _response.data

    async def update(
        self,
        organization_id: str,
        child_id: str,
        *,
        data: UpdateChildRequestData,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ExternalOrganizationResponse:
        """
        Update a child organization. Only the name can be changed.

        Parameters
        ----------
        organization_id : str
            Unique identifier of the parent organization

        child_id : str
            Unique identifier of the child organization

        data : UpdateChildRequestData
            Child organization data for update

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExternalOrganizationResponse
            Updated child organization resource

        Examples
        --------
        import asyncio

        from kard import AsyncKardApi
        from kard.organizations.children import (
            UpdateChildAttributes,
            UpdateChildRequestData,
        )

        client = AsyncKardApi(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.organizations.children.update(
                organization_id="organizationId",
                child_id="childId",
                data=UpdateChildRequestData(
                    attributes=UpdateChildAttributes(),
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(organization_id, child_id, data=data, request_options=request_options)
        return _response.data

    async def delete(
        self, organization_id: str, child_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DeleteResourceResponse:
        """
        Delete a child organization

        Parameters
        ----------
        organization_id : str
            Unique identifier of the parent organization

        child_id : str
            Unique identifier of the child organization

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteResourceResponse

        Examples
        --------
        import asyncio

        from kard import AsyncKardApi

        client = AsyncKardApi(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.organizations.children.delete(
                organization_id="organizationId",
                child_id="childId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(organization_id, child_id, request_options=request_options)
        return _response.data
