# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .external_organization_attributes import ExternalOrganizationAttributes


class ExternalOrganizationResponse(UniversalBaseModel):
    """
    External organization resource response
    """

    type: typing.Literal["organization"] = "organization"
    id: str = pydantic.Field()
    """
    Unique identifier of the organization
    """

    attributes: ExternalOrganizationAttributes

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
