# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...commons.types.card_network import CardNetwork
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from ...internal_organizations.types.enrolled_reward import EnrolledReward


class ExternalOrganizationAttributes(UniversalBaseModel):
    """
    Limited set of organization attributes exposed to external consumers
    """

    name: str = pydantic.Field()
    """
    Name of the organization (uppercase, no spaces)
    """

    enrolled_rewards: typing_extensions.Annotated[
        typing.List[EnrolledReward],
        FieldMetadata(alias="enrolledRewards"),
        pydantic.Field(alias="enrolledRewards", description="Rewards programs the organization is enrolled in"),
    ]
    card_networks: typing_extensions.Annotated[
        typing.List[CardNetwork],
        FieldMetadata(alias="cardNetworks"),
        pydantic.Field(alias="cardNetworks", description="Card networks supported by the organization"),
    ]
    bins: typing.List[str] = pydantic.Field()
    """
    Bank Identification Numbers for the organization
    """

    affiliate_commission_split: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="affiliateCommissionSplit"),
        pydantic.Field(alias="affiliateCommissionSplit", description="Affiliate commission split percentage"),
    ]
    cardlinked_commission_split: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="cardlinkedCommissionSplit"),
        pydantic.Field(alias="cardlinkedCommissionSplit", description="Cardlinked commission split percentage"),
    ]
    cardlinked_user_commission_split: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="cardlinkedUserCommissionSplit"),
        pydantic.Field(
            alias="cardlinkedUserCommissionSplit", description="Cardlinked user commission split percentage"
        ),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
