# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...commons.types.card_network import CardNetwork
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from ...internal_organizations.types.enrolled_reward import EnrolledReward
from ...internal_organizations.types.merchant_network import MerchantNetwork


class ExternalOrganizationAttributes(UniversalBaseModel):
    """
    Limited set of organization attributes exposed to external consumers
    """

    name: str = pydantic.Field()
    """
    Name of the organization (uppercase, no spaces)
    """

    external_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="externalId"),
        pydantic.Field(alias="externalId", description="External identifier for the organization"),
    ] = None
    parent_organization_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="parentOrganizationId"),
        pydantic.Field(alias="parentOrganizationId", description="ID of the parent organization"),
    ] = None
    enrolled_rewards: typing_extensions.Annotated[
        typing.List[EnrolledReward],
        FieldMetadata(alias="enrolledRewards"),
        pydantic.Field(alias="enrolledRewards", description="Rewards programs the organization is enrolled in"),
    ]
    card_networks: typing_extensions.Annotated[
        typing.List[CardNetwork],
        FieldMetadata(alias="cardNetworks"),
        pydantic.Field(alias="cardNetworks", description="Card networks supported by the organization"),
    ]
    merchant_networks: typing_extensions.Annotated[
        typing.Optional[typing.List[MerchantNetwork]],
        FieldMetadata(alias="merchantNetworks"),
        pydantic.Field(alias="merchantNetworks", description="Merchant networks with priority for the organization"),
    ] = None
    national_offers: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="nationalOffers"),
        pydantic.Field(alias="nationalOffers", description="Whether national offers are enabled"),
    ]
    local_offers: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="localOffers"),
        pydantic.Field(alias="localOffers", description="Whether local offers are enabled"),
    ]
    use_attribution: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="useAttribution"),
        pydantic.Field(alias="useAttribution", description="Whether attribution tracking is enabled"),
    ]
    bins: typing.List[str] = pydantic.Field()
    """
    Bank Identification Numbers for the organization
    """

    created_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="When the organization was created (ISO 8601 UTC)"),
    ] = None
    updated_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="updatedAt"),
        pydantic.Field(alias="updatedAt", description="When the organization was last updated (ISO 8601 UTC)"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
