# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .amount import Amount
    from .amount_type import AmountType
    from .asset import Asset
    from .batches_meta import BatchesMeta
    from .batches_response_object import BatchesResponseObject
    from .category_data import CategoryData
    from .category_fields import CategoryFields
    from .category_identifier import CategoryIdentifier
    from .category_included import CategoryIncluded
    from .category_relationship import CategoryRelationship
    from .category_relationship_object import CategoryRelationshipObject
    from .commission import Commission
    from .component_type import ComponentType
    from .coordinates import Coordinates
    from .eligibility_location_address import EligibilityLocationAddress
    from .eligibility_location_included import EligibilityLocationIncluded
    from .eligibility_offer_included import EligibilityOfferIncluded
    from .eligibility_offer_relationship import EligibilityOfferRelationship
    from .location_attributes import LocationAttributes
    from .location_data import LocationData
    from .location_partner_id import LocationPartnerId
    from .location_partner_id_type import LocationPartnerIdType
    from .location_relationships import LocationRelationships
    from .location_sort_options import LocationSortOptions
    from .locations_response_object import LocationsResponseObject
    from .offer_common_fields import OfferCommonFields
    from .offer_data_union import OfferDataUnion, OfferDataUnion_StandardOffer
    from .offer_relationship import OfferRelationship
    from .offer_sort_options import OfferSortOptions
    from .offers_meta import OffersMeta
    from .offers_response_object import OffersResponseObject
    from .operation_hours import OperationHours
    from .operation_period import OperationPeriod
    from .operation_time import OperationTime
    from .placement_batch_attributes import PlacementBatchAttributes
    from .placement_batch_data import PlacementBatchData
    from .placement_content_response import PlacementContentResponse
    from .standard_offer import StandardOffer
    from .standard_offer_core import StandardOfferCore
    from .standard_offer_fields import StandardOfferFields
_dynamic_imports: typing.Dict[str, str] = {
    "Amount": ".amount",
    "AmountType": ".amount_type",
    "Asset": ".asset",
    "BatchesMeta": ".batches_meta",
    "BatchesResponseObject": ".batches_response_object",
    "CategoryData": ".category_data",
    "CategoryFields": ".category_fields",
    "CategoryIdentifier": ".category_identifier",
    "CategoryIncluded": ".category_included",
    "CategoryRelationship": ".category_relationship",
    "CategoryRelationshipObject": ".category_relationship_object",
    "Commission": ".commission",
    "ComponentType": ".component_type",
    "Coordinates": ".coordinates",
    "EligibilityLocationAddress": ".eligibility_location_address",
    "EligibilityLocationIncluded": ".eligibility_location_included",
    "EligibilityOfferIncluded": ".eligibility_offer_included",
    "EligibilityOfferRelationship": ".eligibility_offer_relationship",
    "LocationAttributes": ".location_attributes",
    "LocationData": ".location_data",
    "LocationPartnerId": ".location_partner_id",
    "LocationPartnerIdType": ".location_partner_id_type",
    "LocationRelationships": ".location_relationships",
    "LocationSortOptions": ".location_sort_options",
    "LocationsResponseObject": ".locations_response_object",
    "OfferCommonFields": ".offer_common_fields",
    "OfferDataUnion": ".offer_data_union",
    "OfferDataUnion_StandardOffer": ".offer_data_union",
    "OfferRelationship": ".offer_relationship",
    "OfferSortOptions": ".offer_sort_options",
    "OffersMeta": ".offers_meta",
    "OffersResponseObject": ".offers_response_object",
    "OperationHours": ".operation_hours",
    "OperationPeriod": ".operation_period",
    "OperationTime": ".operation_time",
    "PlacementBatchAttributes": ".placement_batch_attributes",
    "PlacementBatchData": ".placement_batch_data",
    "PlacementContentResponse": ".placement_content_response",
    "StandardOffer": ".standard_offer",
    "StandardOfferCore": ".standard_offer_core",
    "StandardOfferFields": ".standard_offer_fields",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "Amount",
    "AmountType",
    "Asset",
    "BatchesMeta",
    "BatchesResponseObject",
    "CategoryData",
    "CategoryFields",
    "CategoryIdentifier",
    "CategoryIncluded",
    "CategoryRelationship",
    "CategoryRelationshipObject",
    "Commission",
    "ComponentType",
    "Coordinates",
    "EligibilityLocationAddress",
    "EligibilityLocationIncluded",
    "EligibilityOfferIncluded",
    "EligibilityOfferRelationship",
    "LocationAttributes",
    "LocationData",
    "LocationPartnerId",
    "LocationPartnerIdType",
    "LocationRelationships",
    "LocationSortOptions",
    "LocationsResponseObject",
    "OfferCommonFields",
    "OfferDataUnion",
    "OfferDataUnion_StandardOffer",
    "OfferRelationship",
    "OfferSortOptions",
    "OffersMeta",
    "OffersResponseObject",
    "OperationHours",
    "OperationPeriod",
    "OperationTime",
    "PlacementBatchAttributes",
    "PlacementBatchData",
    "PlacementContentResponse",
    "StandardOffer",
    "StandardOfferCore",
    "StandardOfferFields",
]
