# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata


class BatchesMeta(UniversalBaseModel):
    """
    Metadata about the placement.
    """

    placement_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="placementName"),
        pydantic.Field(
            alias="placementName", description="Display name of the placement, resolved server-side from its id."
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
