# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .placement_batch_data import PlacementBatchData


class BatchesResponseObject(UniversalBaseModel):
    """
    Ordered list of slots for a batch-activation or group placement, with freshness fields and per-slot offer sets.
    """

    data: typing.List[PlacementBatchData]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
