# This file was auto-generated by Fern from our API Definition.

import typing

ComponentType = typing.Union[
    typing.Literal["shortDescription", "longDescription", "cta", "tags", "detailTags"], typing.Any
]
