# This file was auto-generated by Fern from our API Definition.

import typing

ComponentType = typing.Union[
    typing.Literal[
        "shortDescription", "longDescription", "baseReward", "boostedReward", "cta", "tags", "detailTags", "logoFlare"
    ],
    typing.Any,
]
