# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from .button_style import ButtonStyle
from .cta_action import CtaAction


class CtaComponent(UniversalBaseModel):
    """
    Call-to-action button component for offers
    """

    button_text: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="buttonText"),
        pydantic.Field(alias="buttonText", description="Text to display on the button"),
    ]
    button_style: typing_extensions.Annotated[
        ButtonStyle,
        FieldMetadata(alias="buttonStyle"),
        pydantic.Field(alias="buttonStyle", description="Style of the button"),
    ]
    action: typing.Optional[CtaAction] = pydantic.Field(default=None)
    """
    Action to perform when the button is clicked
    """

    start_icon: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="startIcon"),
        pydantic.Field(alias="startIcon", description="Icon identifier to display on the button"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
