# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CtaAction(UniversalBaseModel):
    """
    Action configuration for CTA button
    """

    url: str = pydantic.Field()
    """
    URL endpoint to call when button is clicked
    """

    method: str = pydantic.Field()
    """
    HTTP method to use (e.g., POST)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
