# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class LocationRating(UniversalBaseModel):
    """
    Customer rating for a location.
    """

    value: float = pydantic.Field()
    """
    Restaurant star rating. Rating is out of 5.
    """

    count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of ratings the score is based on. Null when a count is not available.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
