# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from .logo_flare_badge import LogoFlareBadge
from .logo_flare_border_color import LogoFlareBorderColor


class LogoFlare(UniversalBaseModel):
    """
    Logo flare configuration for offer display
    """

    border_color: typing_extensions.Annotated[
        LogoFlareBorderColor,
        FieldMetadata(alias="borderColor"),
        pydantic.Field(alias="borderColor", description="Border color style for the logo flare"),
    ]
    badge: typing.Optional[LogoFlareBadge] = pydantic.Field(default=None)
    """
    Optional badge to display on the logo
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
