# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .logo_flare_badge_position import LogoFlareBadgePosition


class LogoFlareBadge(UniversalBaseModel):
    """
    Badge configuration for logo flare
    """

    icon: str = pydantic.Field()
    """
    Icon identifier for the badge
    """

    position: LogoFlareBadgePosition = pydantic.Field()
    """
    Position of the badge on the logo
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
