# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from .category_included import CategoryIncluded


class OffersMeta(UniversalBaseModel):
    """
    Metadata about the full result set across all pages
    """

    available_categories: typing_extensions.Annotated[
        typing.Optional[typing.List[CategoryIncluded]],
        FieldMetadata(alias="availableCategories"),
        pydantic.Field(
            alias="availableCategories",
            description="All distinct categories available across the entire filtered result set, not just the current page",
        ),
    ] = None
    placement_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="placementName"),
        pydantic.Field(
            alias="placementName",
            description="Display name of the placement, resolved server-side from its id. Populated only on the Get Placement Content endpoint; absent on the Get Offers By User endpoint.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
