# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from .cta_component import CtaComponent


class OfferComponents(UniversalBaseModel):
    """
    UI component data for rendering offer details
    """

    short_description: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="shortDescription")] = (
        pydantic.Field(default=None)
    )
    """
    Short description for the offer
    """

    long_description: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="longDescription")] = (
        pydantic.Field(default=None)
    )
    """
    Long description for the offer
    """

    base_reward: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="baseReward")] = pydantic.Field(
        default=None
    )
    """
    Formatted reward string
    """

    cta: typing.Optional[CtaComponent] = pydantic.Field(default=None)
    """
    Call-to-action button component
    """

    tags: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Tags for the offer
    """

    detail_tags: typing_extensions.Annotated[typing.Optional[typing.List[str]], FieldMetadata(alias="detailTags")] = (
        pydantic.Field(default=None)
    )
    """
    Detail tags for the offer
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
