# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from .cta_component import CtaComponent
from .logo_flare import LogoFlare
from .progress_bar import ProgressBar


class OfferComponents(UniversalBaseModel):
    """
    UI component data for rendering offer details
    """

    short_description: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="shortDescription"),
        pydantic.Field(alias="shortDescription", description="Short description for the offer"),
    ] = None
    long_description: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="longDescription"),
        pydantic.Field(alias="longDescription", description="Long description for the offer"),
    ] = None
    base_reward: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="baseReward"),
        pydantic.Field(alias="baseReward", description="Formatted reward string"),
    ] = None
    boosted_reward: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="boostedReward"),
        pydantic.Field(alias="boostedReward", description="Formatted boosted reward string"),
    ] = None
    cta: typing.Optional[CtaComponent] = pydantic.Field(default=None)
    """
    Call-to-action button component
    """

    tags: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Tags for the offer
    """

    detail_tags: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="detailTags"),
        pydantic.Field(alias="detailTags", description="Detail tags for the offer"),
    ] = None
    logo_flare: typing_extensions.Annotated[
        typing.Optional[LogoFlare],
        FieldMetadata(alias="logoFlare"),
        pydantic.Field(alias="logoFlare", description="Logo flare configuration for the offer"),
    ] = None
    progress_bar: typing_extensions.Annotated[
        typing.Optional[ProgressBar],
        FieldMetadata(alias="progressBar"),
        pydantic.Field(alias="progressBar", description="Progress bar component for tracking offer redemptions"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
