# This file was auto-generated by Fern from our API Definition.

import typing

from .offer_data_union import OfferDataUnion
from .placement_batch_data import PlacementBatchData

PlacementContentData = typing.Union[OfferDataUnion, PlacementBatchData]
