# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .placement_batch_attributes import PlacementBatchAttributes


class PlacementBatchData(UniversalBaseModel):
    """
    One slot in a batch-activation placement, with freshness fields and the offers that resolve under the slot's content strategy.
    """

    id: str = pydantic.Field()
    """
    Stable identifier for the slot within the placement
    """

    type: typing.Literal["placementBatch"] = "placementBatch"
    attributes: PlacementBatchAttributes

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
