# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from .asset import Asset
from .offer_components import OfferComponents
from .offer_data_union import OfferDataUnion


class PlacementBatchAttributes(UniversalBaseModel):
    """
    Attributes of a placement batch slot.
    """

    name: str = pydantic.Field()
    """
    Display name for the slot. Falls back to the slot's customer-defined alias, or — when the alias is absent — the name of the placement referenced by the slot.
    """

    is_active: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="isActive"),
        pydantic.Field(
            alias="isActive",
            description='Whether the slot is still considered "fresh" for the user. Set to false only when the slot\'s `expiresAt` is in the past AND the slot resolves to a non-empty offer set; an empty offer set keeps the slot active so partner UIs do not promote "tap to refresh" with nothing to show.',
        ),
    ]
    last_activated_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="lastActivatedAt"),
        pydantic.Field(
            alias="lastActivatedAt",
            description="Timestamp of the most recent placementSlotAttribution ACTIVATE event for this (user, placement, slot). Absent for cold slots that have never been activated.",
        ),
    ] = None
    expires_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="expiresAt"),
        pydantic.Field(
            alias="expiresAt",
            description="Computed as `lastActivatedAt + placement.refreshInterval`. Absent for cold slots that have never been activated.",
        ),
    ] = None
    components: typing.Optional[OfferComponents] = pydantic.Field(default=None)
    """
    Slot-level UI components. Carries a `cta` (POST to the slot's activate endpoint) when the slot has no active (non-expired) activation, or a `logoFlare` decoration when it does — mutually exclusive on a single slot.
    """

    assets: typing.Optional[typing.List[Asset]] = pydantic.Field(default=None)
    """
    Slot-level visual assets. Currently a single `IMG_VIEW` SVG showing the slot's initials, themed via the `--icon-fill` CSS custom property.
    """

    offers: typing.List[OfferDataUnion] = pydantic.Field()
    """
    The set of offers eligible for the user under this slot's content strategy.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
