# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ProgressBarSegmentProgress(UniversalBaseModel):
    """
    Fill state of a single segment node, expressed as completed of total.
    """

    completed: int = pydantic.Field()
    """
    Units completed within the current segment.
    """

    total: int = pydantic.Field()
    """
    Total units required to complete the current segment.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
