# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata


class ProgressBar(UniversalBaseModel):
    """
    Progress bar component for tracking offer redemption progress
    """

    total: int = pydantic.Field()
    """
    Total number of redemptions allowed
    """

    current_progress: typing_extensions.Annotated[int, FieldMetadata(alias="currentProgress")] = pydantic.Field()
    """
    Number of redemptions the user has completed
    """

    label: str = pydantic.Field()
    """
    Formatted label for the progress bar
    """

    segmented: bool = pydantic.Field()
    """
    Whether the progress bar should be displayed as segmented
    """

    segment_icon: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="segmentIcon")] = (
        pydantic.Field(default=None)
    )
    """
    SVG icon to use for each segment when the progress bar is segmented
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
