# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .progress_bar_label_position import ProgressBarLabelPosition


class ProgressBarLabel(UniversalBaseModel):
    """
    Progress bar label configuration
    """

    text: str = pydantic.Field()
    """
    Text content for the label
    """

    position: ProgressBarLabelPosition = pydantic.Field()
    """
    Position where the label should render
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
