# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .progress_bar_label import ProgressBarLabel


class ProgressBarLabels(UniversalBaseModel):
    """
    Labels to render around the progress bar in different layouts
    """

    details: ProgressBarLabel = pydantic.Field()
    """
    Label configuration for the details view
    """

    default: ProgressBarLabel = pydantic.Field()
    """
    Label configuration for the default view
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
