# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .progress_bar_segment_position import ProgressBarSegmentPosition


class ProgressBarSegment(UniversalBaseModel):
    """
    Segment configuration for a specific layout
    """

    icon: typing.Optional[str] = pydantic.Field(default=None)
    """
    SVG icon to use for each segment
    """

    position: ProgressBarSegmentPosition = pydantic.Field()
    """
    Position of the segment within the layout
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
