# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .child_organization_attributes import ChildOrganizationAttributes
    from .child_organization_list_response import ChildOrganizationListResponse
    from .child_organization_response import ChildOrganizationResponse
    from .create_child_attributes import CreateChildAttributes
    from .create_child_request_body import CreateChildRequestBody
    from .create_child_request_data import CreateChildRequestData
    from .update_child_attributes import UpdateChildAttributes
    from .update_child_request_body import UpdateChildRequestBody
    from .update_child_request_data import UpdateChildRequestData
_dynamic_imports: typing.Dict[str, str] = {
    "ChildOrganizationAttributes": ".child_organization_attributes",
    "ChildOrganizationListResponse": ".child_organization_list_response",
    "ChildOrganizationResponse": ".child_organization_response",
    "CreateChildAttributes": ".create_child_attributes",
    "CreateChildRequestBody": ".create_child_request_body",
    "CreateChildRequestData": ".create_child_request_data",
    "UpdateChildAttributes": ".update_child_attributes",
    "UpdateChildRequestBody": ".update_child_request_body",
    "UpdateChildRequestData": ".update_child_request_data",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ChildOrganizationAttributes",
    "ChildOrganizationListResponse",
    "ChildOrganizationResponse",
    "CreateChildAttributes",
    "CreateChildRequestBody",
    "CreateChildRequestData",
    "UpdateChildAttributes",
    "UpdateChildRequestBody",
    "UpdateChildRequestData",
]
