# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....commons.types.links import Links
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....internal_organizations.types.organization_pagination_metadata import OrganizationPaginationMetadata
from .child_organization_response import ChildOrganizationResponse


class ChildOrganizationListResponse(UniversalBaseModel):
    """
    Paginated list of child organizations
    """

    data: typing.List[ChildOrganizationResponse] = pydantic.Field()
    """
    Array of child organization resources
    """

    links: typing.Optional[Links] = None
    meta: typing.Optional[OrganizationPaginationMetadata] = pydantic.Field(default=None)
    """
    Pagination metadata
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
