# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata


class ChildOrganizationAttributes(UniversalBaseModel):
    """
    Limited set of child organization attributes exposed to external consumers
    """

    name: str = pydantic.Field()
    """
    Name of the child organization (uppercase, no spaces)
    """

    external_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="externalId"),
        pydantic.Field(alias="externalId", description="External identifier for the child organization"),
    ] = None
    bins: typing.List[str] = pydantic.Field()
    """
    Bank Identification Numbers for the child organization
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
