# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata


class CreateChildAttributes(UniversalBaseModel):
    """
    Attributes for creating a child organization. Only name is required. All other fields are optional and default to the parent organization's values.

    Examples
    --------
    from kard.organizations.children import CreateChildAttributes

    CreateChildAttributes(
        name="ACMECHILDBANK",
        external_id="ext-123",
        bins=["123456", "789012"],
    )
    """

    name: str = pydantic.Field()
    """
    Name of the child organization (must be uppercase, no spaces)
    """

    external_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="externalId"),
        pydantic.Field(alias="externalId", description="External identifier for the child organization"),
    ] = None
    bins: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Bank Identification Numbers for the child organization
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
