# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .update_child_request_data import UpdateChildRequestData


class UpdateChildRequestBody(UniversalBaseModel):
    """
    Request body for updating a child organization
    """

    data: UpdateChildRequestData = pydantic.Field()
    """
    Child organization data for update
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
