# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .update_child_attributes import UpdateChildAttributes


class UpdateChildRequestData(UniversalBaseModel):
    """
    Child organization data structure for update
    """

    type: typing.Literal["organization"] = pydantic.Field(default="organization")
    """
    Resource type identifier
    """

    attributes: UpdateChildAttributes = pydantic.Field()
    """
    Child organization attributes for update
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
