# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        BatchActivationPlacementAttributes,
        BatchActivationPlacementData,
        BatchActivationSlot,
        Cadence,
        CadenceFrequency,
        CreateBatchActivationAttributes,
        CreateBatchActivationPlacementData,
        CreateBatchActivationSlot,
        CreateMainPageAttributes,
        CreateMainPagePlacementData,
        CreatePlacementDataUnion,
        CreatePlacementDataUnion_PlacementBatchActivation,
        CreatePlacementDataUnion_PlacementMainPage,
        CreatePlacementDataUnion_PlacementPushNotification,
        CreatePlacementRequestBody,
        CreatePushNotificationAttributes,
        CreatePushNotificationPlacementData,
        DayOfWeek,
        MainPagePlacementAttributes,
        MainPagePlacementData,
        PlacementFormatUnion,
        PlacementFormatUnion_PlacementBatchActivation,
        PlacementFormatUnion_PlacementMainPage,
        PlacementFormatUnion_PlacementPushNotification,
        PlacementListResponse,
        PlacementResource,
        PlacementTypeFilter,
        PushNotificationPlacementAttributes,
        PushNotificationPlacementData,
        UpdateBatchActivationAttributes,
        UpdateBatchActivationPlacementData,
        UpdateBatchActivationSlot,
        UpdateMainPageAttributes,
        UpdateMainPagePlacementData,
        UpdatePlacementDataUnion,
        UpdatePlacementDataUnion_PlacementBatchActivation,
        UpdatePlacementDataUnion_PlacementMainPage,
        UpdatePlacementDataUnion_PlacementPushNotification,
        UpdatePlacementRequestBody,
        UpdatePushNotificationAttributes,
        UpdatePushNotificationPlacementData,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "BatchActivationPlacementAttributes": ".types",
    "BatchActivationPlacementData": ".types",
    "BatchActivationSlot": ".types",
    "Cadence": ".types",
    "CadenceFrequency": ".types",
    "CreateBatchActivationAttributes": ".types",
    "CreateBatchActivationPlacementData": ".types",
    "CreateBatchActivationSlot": ".types",
    "CreateMainPageAttributes": ".types",
    "CreateMainPagePlacementData": ".types",
    "CreatePlacementDataUnion": ".types",
    "CreatePlacementDataUnion_PlacementBatchActivation": ".types",
    "CreatePlacementDataUnion_PlacementMainPage": ".types",
    "CreatePlacementDataUnion_PlacementPushNotification": ".types",
    "CreatePlacementRequestBody": ".types",
    "CreatePushNotificationAttributes": ".types",
    "CreatePushNotificationPlacementData": ".types",
    "DayOfWeek": ".types",
    "MainPagePlacementAttributes": ".types",
    "MainPagePlacementData": ".types",
    "PlacementFormatUnion": ".types",
    "PlacementFormatUnion_PlacementBatchActivation": ".types",
    "PlacementFormatUnion_PlacementMainPage": ".types",
    "PlacementFormatUnion_PlacementPushNotification": ".types",
    "PlacementListResponse": ".types",
    "PlacementResource": ".types",
    "PlacementTypeFilter": ".types",
    "PushNotificationPlacementAttributes": ".types",
    "PushNotificationPlacementData": ".types",
    "UpdateBatchActivationAttributes": ".types",
    "UpdateBatchActivationPlacementData": ".types",
    "UpdateBatchActivationSlot": ".types",
    "UpdateMainPageAttributes": ".types",
    "UpdateMainPagePlacementData": ".types",
    "UpdatePlacementDataUnion": ".types",
    "UpdatePlacementDataUnion_PlacementBatchActivation": ".types",
    "UpdatePlacementDataUnion_PlacementMainPage": ".types",
    "UpdatePlacementDataUnion_PlacementPushNotification": ".types",
    "UpdatePlacementRequestBody": ".types",
    "UpdatePushNotificationAttributes": ".types",
    "UpdatePushNotificationPlacementData": ".types",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "BatchActivationPlacementAttributes",
    "BatchActivationPlacementData",
    "BatchActivationSlot",
    "Cadence",
    "CadenceFrequency",
    "CreateBatchActivationAttributes",
    "CreateBatchActivationPlacementData",
    "CreateBatchActivationSlot",
    "CreateMainPageAttributes",
    "CreateMainPagePlacementData",
    "CreatePlacementDataUnion",
    "CreatePlacementDataUnion_PlacementBatchActivation",
    "CreatePlacementDataUnion_PlacementMainPage",
    "CreatePlacementDataUnion_PlacementPushNotification",
    "CreatePlacementRequestBody",
    "CreatePushNotificationAttributes",
    "CreatePushNotificationPlacementData",
    "DayOfWeek",
    "MainPagePlacementAttributes",
    "MainPagePlacementData",
    "PlacementFormatUnion",
    "PlacementFormatUnion_PlacementBatchActivation",
    "PlacementFormatUnion_PlacementMainPage",
    "PlacementFormatUnion_PlacementPushNotification",
    "PlacementListResponse",
    "PlacementResource",
    "PlacementTypeFilter",
    "PushNotificationPlacementAttributes",
    "PushNotificationPlacementData",
    "UpdateBatchActivationAttributes",
    "UpdateBatchActivationPlacementData",
    "UpdateBatchActivationSlot",
    "UpdateMainPageAttributes",
    "UpdateMainPagePlacementData",
    "UpdatePlacementDataUnion",
    "UpdatePlacementDataUnion_PlacementBatchActivation",
    "UpdatePlacementDataUnion_PlacementMainPage",
    "UpdatePlacementDataUnion_PlacementPushNotification",
    "UpdatePlacementRequestBody",
    "UpdatePushNotificationAttributes",
    "UpdatePushNotificationPlacementData",
]
