# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...internal_organizations.types.delete_resource_response import DeleteResourceResponse
from .raw_client import AsyncRawPlacementsClient, RawPlacementsClient
from .types.create_placement_data_union import CreatePlacementDataUnion
from .types.placement_format_union import PlacementFormatUnion
from .types.placement_list_response import PlacementListResponse
from .types.placement_type_filter import PlacementTypeFilter
from .types.update_placement_data_union import UpdatePlacementDataUnion

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class PlacementsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPlacementsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPlacementsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPlacementsClient
        """
        return self._raw_client

    def create(
        self,
        organization_id: str,
        *,
        data: CreatePlacementDataUnion,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PlacementFormatUnion:
        """
        Create a placement for the organization. Use type "placementMainPage" for main-page placements (requires name and availableSlots) or "placementPushNotification" for push-notification placements (requires name and cadence; availableSlots is automatically set to 1).

        Parameters
        ----------
        organization_id : str
            Unique identifier of the organization

        data : CreatePlacementDataUnion
            Placement data for creation

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PlacementFormatUnion
            Created placement resource

        Examples
        --------
        from kard import KardApi
        from kard.organizations.placements import (
            CreateMainPageAttributes,
            CreatePlacementDataUnion_PlacementMainPage,
        )

        client = KardApi(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.organizations.placements.create(
            organization_id="org-123",
            data=CreatePlacementDataUnion_PlacementMainPage(
                attributes=CreateMainPageAttributes(
                    name="Homepage Banner",
                    available_slots=5,
                ),
            ),
        )
        """
        _response = self._raw_client.create(organization_id, data=data, request_options=request_options)
        return _response.data

    def list(
        self,
        organization_id: str,
        *,
        filter_type: typing.Optional[PlacementTypeFilter] = None,
        filter_name: typing.Optional[str] = None,
        page_after: typing.Optional[str] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PlacementListResponse:
        """
        List placements belonging to the authenticated organization

        Parameters
        ----------
        organization_id : str
            Unique identifier of the organization

        filter_type : typing.Optional[PlacementTypeFilter]
            Filter by placement type (placementMainPage or placementPushNotification)

        filter_name : typing.Optional[str]
            Filter by exact placement name (unique within an organization per type)

        page_after : typing.Optional[str]
            Cursor value for the next page of results

        page_size : typing.Optional[int]
            Maximum number of records to return [1 - 200] (default = 200)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PlacementListResponse
            Paginated list of placements

        Examples
        --------
        from kard import KardApi

        client = KardApi(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.organizations.placements.list(
            organization_id="organizationId",
        )
        """
        _response = self._raw_client.list(
            organization_id,
            filter_type=filter_type,
            filter_name=filter_name,
            page_after=page_after,
            page_size=page_size,
            request_options=request_options,
        )
        return _response.data

    def get(
        self, organization_id: str, placement_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PlacementFormatUnion:
        """
        Retrieve a specific placement

        Parameters
        ----------
        organization_id : str
            Unique identifier of the organization

        placement_id : str
            Unique identifier of the placement (UUID v7)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PlacementFormatUnion
            Placement resource

        Examples
        --------
        from kard import KardApi

        client = KardApi(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.organizations.placements.get(
            organization_id="organizationId",
            placement_id="placementId",
        )
        """
        _response = self._raw_client.get(organization_id, placement_id, request_options=request_options)
        return _response.data

    def update(
        self,
        organization_id: str,
        placement_id: str,
        *,
        data: UpdatePlacementDataUnion,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PlacementFormatUnion:
        """
        Replace a placement. All fields must be provided. Use type "placementMainPage" or "placementPushNotification" to set the placement kind. If the type is "placementPushNotification", availableSlots is automatically set to 1.

        Parameters
        ----------
        organization_id : str
            Unique identifier of the organization

        placement_id : str
            Unique identifier of the placement (UUID v7)

        data : UpdatePlacementDataUnion
            Placement data for update

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PlacementFormatUnion
            Updated placement resource

        Examples
        --------
        from kard import KardApi
        from kard.organizations.placements import (
            UpdateMainPageAttributes,
            UpdatePlacementDataUnion_PlacementMainPage,
        )

        client = KardApi(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.organizations.placements.update(
            organization_id="organizationId",
            placement_id="placementId",
            data=UpdatePlacementDataUnion_PlacementMainPage(
                attributes=UpdateMainPageAttributes(
                    name="name",
                    available_slots=1,
                ),
            ),
        )
        """
        _response = self._raw_client.update(organization_id, placement_id, data=data, request_options=request_options)
        return _response.data

    def delete(
        self, organization_id: str, placement_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DeleteResourceResponse:
        """
        Delete a placement

        Parameters
        ----------
        organization_id : str
            Unique identifier of the organization

        placement_id : str
            Unique identifier of the placement (UUID v7)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteResourceResponse

        Examples
        --------
        from kard import KardApi

        client = KardApi(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.organizations.placements.delete(
            organization_id="organizationId",
            placement_id="placementId",
        )
        """
        _response = self._raw_client.delete(organization_id, placement_id, request_options=request_options)
        return _response.data


class AsyncPlacementsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPlacementsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPlacementsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPlacementsClient
        """
        return self._raw_client

    async def create(
        self,
        organization_id: str,
        *,
        data: CreatePlacementDataUnion,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PlacementFormatUnion:
        """
        Create a placement for the organization. Use type "placementMainPage" for main-page placements (requires name and availableSlots) or "placementPushNotification" for push-notification placements (requires name and cadence; availableSlots is automatically set to 1).

        Parameters
        ----------
        organization_id : str
            Unique identifier of the organization

        data : CreatePlacementDataUnion
            Placement data for creation

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PlacementFormatUnion
            Created placement resource

        Examples
        --------
        import asyncio

        from kard import AsyncKardApi
        from kard.organizations.placements import (
            CreateMainPageAttributes,
            CreatePlacementDataUnion_PlacementMainPage,
        )

        client = AsyncKardApi(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.organizations.placements.create(
                organization_id="org-123",
                data=CreatePlacementDataUnion_PlacementMainPage(
                    attributes=CreateMainPageAttributes(
                        name="Homepage Banner",
                        available_slots=5,
                    ),
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(organization_id, data=data, request_options=request_options)
        return _response.data

    async def list(
        self,
        organization_id: str,
        *,
        filter_type: typing.Optional[PlacementTypeFilter] = None,
        filter_name: typing.Optional[str] = None,
        page_after: typing.Optional[str] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PlacementListResponse:
        """
        List placements belonging to the authenticated organization

        Parameters
        ----------
        organization_id : str
            Unique identifier of the organization

        filter_type : typing.Optional[PlacementTypeFilter]
            Filter by placement type (placementMainPage or placementPushNotification)

        filter_name : typing.Optional[str]
            Filter by exact placement name (unique within an organization per type)

        page_after : typing.Optional[str]
            Cursor value for the next page of results

        page_size : typing.Optional[int]
            Maximum number of records to return [1 - 200] (default = 200)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PlacementListResponse
            Paginated list of placements

        Examples
        --------
        import asyncio

        from kard import AsyncKardApi

        client = AsyncKardApi(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.organizations.placements.list(
                organization_id="organizationId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            organization_id,
            filter_type=filter_type,
            filter_name=filter_name,
            page_after=page_after,
            page_size=page_size,
            request_options=request_options,
        )
        return _response.data

    async def get(
        self, organization_id: str, placement_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PlacementFormatUnion:
        """
        Retrieve a specific placement

        Parameters
        ----------
        organization_id : str
            Unique identifier of the organization

        placement_id : str
            Unique identifier of the placement (UUID v7)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PlacementFormatUnion
            Placement resource

        Examples
        --------
        import asyncio

        from kard import AsyncKardApi

        client = AsyncKardApi(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.organizations.placements.get(
                organization_id="organizationId",
                placement_id="placementId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(organization_id, placement_id, request_options=request_options)
        return _response.data

    async def update(
        self,
        organization_id: str,
        placement_id: str,
        *,
        data: UpdatePlacementDataUnion,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PlacementFormatUnion:
        """
        Replace a placement. All fields must be provided. Use type "placementMainPage" or "placementPushNotification" to set the placement kind. If the type is "placementPushNotification", availableSlots is automatically set to 1.

        Parameters
        ----------
        organization_id : str
            Unique identifier of the organization

        placement_id : str
            Unique identifier of the placement (UUID v7)

        data : UpdatePlacementDataUnion
            Placement data for update

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PlacementFormatUnion
            Updated placement resource

        Examples
        --------
        import asyncio

        from kard import AsyncKardApi
        from kard.organizations.placements import (
            UpdateMainPageAttributes,
            UpdatePlacementDataUnion_PlacementMainPage,
        )

        client = AsyncKardApi(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.organizations.placements.update(
                organization_id="organizationId",
                placement_id="placementId",
                data=UpdatePlacementDataUnion_PlacementMainPage(
                    attributes=UpdateMainPageAttributes(
                        name="name",
                        available_slots=1,
                    ),
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            organization_id, placement_id, data=data, request_options=request_options
        )
        return _response.data

    async def delete(
        self, organization_id: str, placement_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DeleteResourceResponse:
        """
        Delete a placement

        Parameters
        ----------
        organization_id : str
            Unique identifier of the organization

        placement_id : str
            Unique identifier of the placement (UUID v7)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteResourceResponse

        Examples
        --------
        import asyncio

        from kard import AsyncKardApi

        client = AsyncKardApi(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.organizations.placements.delete(
                organization_id="organizationId",
                placement_id="placementId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(organization_id, placement_id, request_options=request_options)
        return _response.data
