# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .cadence import Cadence
    from .cadence_frequency import CadenceFrequency
    from .create_main_page_attributes import CreateMainPageAttributes
    from .create_main_page_placement_data import CreateMainPagePlacementData
    from .create_placement_data_union import (
        CreatePlacementDataUnion,
        CreatePlacementDataUnion_PlacementMainPage,
        CreatePlacementDataUnion_PlacementPushNotification,
    )
    from .create_placement_request_body import CreatePlacementRequestBody
    from .create_push_notification_attributes import CreatePushNotificationAttributes
    from .create_push_notification_placement_data import CreatePushNotificationPlacementData
    from .day_of_week import DayOfWeek
    from .main_page_placement_attributes import MainPagePlacementAttributes
    from .main_page_placement_data import MainPagePlacementData
    from .placement_format_union import (
        PlacementFormatUnion,
        PlacementFormatUnion_PlacementMainPage,
        PlacementFormatUnion_PlacementPushNotification,
    )
    from .placement_list_response import PlacementListResponse
    from .push_notification_placement_attributes import PushNotificationPlacementAttributes
    from .push_notification_placement_data import PushNotificationPlacementData
    from .update_main_page_attributes import UpdateMainPageAttributes
    from .update_main_page_placement_data import UpdateMainPagePlacementData
    from .update_placement_data_union import (
        UpdatePlacementDataUnion,
        UpdatePlacementDataUnion_PlacementMainPage,
        UpdatePlacementDataUnion_PlacementPushNotification,
    )
    from .update_placement_request_body import UpdatePlacementRequestBody
    from .update_push_notification_attributes import UpdatePushNotificationAttributes
    from .update_push_notification_placement_data import UpdatePushNotificationPlacementData
_dynamic_imports: typing.Dict[str, str] = {
    "Cadence": ".cadence",
    "CadenceFrequency": ".cadence_frequency",
    "CreateMainPageAttributes": ".create_main_page_attributes",
    "CreateMainPagePlacementData": ".create_main_page_placement_data",
    "CreatePlacementDataUnion": ".create_placement_data_union",
    "CreatePlacementDataUnion_PlacementMainPage": ".create_placement_data_union",
    "CreatePlacementDataUnion_PlacementPushNotification": ".create_placement_data_union",
    "CreatePlacementRequestBody": ".create_placement_request_body",
    "CreatePushNotificationAttributes": ".create_push_notification_attributes",
    "CreatePushNotificationPlacementData": ".create_push_notification_placement_data",
    "DayOfWeek": ".day_of_week",
    "MainPagePlacementAttributes": ".main_page_placement_attributes",
    "MainPagePlacementData": ".main_page_placement_data",
    "PlacementFormatUnion": ".placement_format_union",
    "PlacementFormatUnion_PlacementMainPage": ".placement_format_union",
    "PlacementFormatUnion_PlacementPushNotification": ".placement_format_union",
    "PlacementListResponse": ".placement_list_response",
    "PushNotificationPlacementAttributes": ".push_notification_placement_attributes",
    "PushNotificationPlacementData": ".push_notification_placement_data",
    "UpdateMainPageAttributes": ".update_main_page_attributes",
    "UpdateMainPagePlacementData": ".update_main_page_placement_data",
    "UpdatePlacementDataUnion": ".update_placement_data_union",
    "UpdatePlacementDataUnion_PlacementMainPage": ".update_placement_data_union",
    "UpdatePlacementDataUnion_PlacementPushNotification": ".update_placement_data_union",
    "UpdatePlacementRequestBody": ".update_placement_request_body",
    "UpdatePushNotificationAttributes": ".update_push_notification_attributes",
    "UpdatePushNotificationPlacementData": ".update_push_notification_placement_data",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "Cadence",
    "CadenceFrequency",
    "CreateMainPageAttributes",
    "CreateMainPagePlacementData",
    "CreatePlacementDataUnion",
    "CreatePlacementDataUnion_PlacementMainPage",
    "CreatePlacementDataUnion_PlacementPushNotification",
    "CreatePlacementRequestBody",
    "CreatePushNotificationAttributes",
    "CreatePushNotificationPlacementData",
    "DayOfWeek",
    "MainPagePlacementAttributes",
    "MainPagePlacementData",
    "PlacementFormatUnion",
    "PlacementFormatUnion_PlacementMainPage",
    "PlacementFormatUnion_PlacementPushNotification",
    "PlacementListResponse",
    "PushNotificationPlacementAttributes",
    "PushNotificationPlacementData",
    "UpdateMainPageAttributes",
    "UpdateMainPagePlacementData",
    "UpdatePlacementDataUnion",
    "UpdatePlacementDataUnion_PlacementMainPage",
    "UpdatePlacementDataUnion_PlacementPushNotification",
    "UpdatePlacementRequestBody",
    "UpdatePushNotificationAttributes",
    "UpdatePushNotificationPlacementData",
]
