# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata


class BatchActivationSlotAttributes(UniversalBaseModel):
    """
    Attributes block for a `batchActivationSlot` resource.
    """

    alias: str = pydantic.Field()
    """
    Customer-defined alias for the slot, unique within the placement.
    """

    short_description: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="shortDescription"),
        pydantic.Field(
            alias="shortDescription", description="Optional short description of the slot, limited to 50 characters."
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
