# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .batch_activation_placement_attributes import BatchActivationPlacementAttributes
from .batch_activation_placement_relationships import BatchActivationPlacementRelationships


class BatchActivationPlacementData(UniversalBaseModel):
    """
    Batch-activation placement resource data
    """

    id: str = pydantic.Field()
    """
    Unique identifier of the placement (UUID v7)
    """

    attributes: BatchActivationPlacementAttributes
    relationships: BatchActivationPlacementRelationships = pydantic.Field()
    """
    JSON:API relationships for the placement. Always present on a batch-activation placement; the `slots` to-many relationship lists the slot resource identifiers.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
