# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from .cadence_frequency import CadenceFrequency
from .day_of_week import DayOfWeek


class Cadence(UniversalBaseModel):
    """
    Cadence schedule for push notification placements
    """

    frequency: CadenceFrequency = pydantic.Field()
    """
    Delivery frequency
    """

    time_of_day: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="timeOfDay"),
        pydantic.Field(alias="timeOfDay", description="Optional time of day in HH:mm format (24-hour, UTC)"),
    ] = None
    day_of_week: typing_extensions.Annotated[
        typing.Optional[DayOfWeek],
        FieldMetadata(alias="dayOfWeek"),
        pydantic.Field(
            alias="dayOfWeek", description="Day of the week to deliver (used when frequency is WEEKLY, defaults to MON)"
        ),
    ] = None
    day_of_month: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="dayOfMonth"),
        pydantic.Field(
            alias="dayOfMonth",
            description="Day of the month to deliver, 1-31 (used when frequency is MONTHLY, defaults to 1)",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
