# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from .cadence import Cadence


class CreateEmailAttributes(UniversalBaseModel):
    """
    Attributes for creating an email placement

    Examples
    --------
    from kard.organizations.placements import Cadence, CreateEmailAttributes

    CreateEmailAttributes(
        name="Weekly Deals Email",
        available_slots=10,
        cadence=Cadence(
            frequency="WEEKLY",
            time_of_day="10:00",
            day_of_week="MON",
        ),
    )
    """

    name: str = pydantic.Field()
    """
    Name of the placement
    """

    available_slots: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="availableSlots"),
        pydantic.Field(alias="availableSlots", description="Number of available slots (minimum 1)"),
    ]
    cadence: Cadence = pydantic.Field()
    """
    Delivery cadence for the email
    """

    content_strategy_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="contentStrategyId"),
        pydantic.Field(alias="contentStrategyId", description="ID of the content strategy to link this placement to"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
