# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata


class CreateBatchActivationSlot(UniversalBaseModel):
    """
    A slot in a batch-activation placement at creation time
    """

    placement_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="placementId"),
        pydantic.Field(
            alias="placementId",
            description="ID of another placement that fills this slot. The referenced placement provides both the content strategy and the limit on the number of offers available to the slot.",
        ),
    ]
    alias: str = pydantic.Field()
    """
    Customer-defined alias for the slot, unique within the placement
    """

    short_description: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="shortDescription"),
        pydantic.Field(
            alias="shortDescription", description="Optional short description of the slot, limited to 50 characters"
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
