# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata


class CreateMainPageAttributes(UniversalBaseModel):
    """
    Attributes for creating a main-page placement

    Examples
    --------
    from kard.organizations.placements import CreateMainPageAttributes

    CreateMainPageAttributes(
        name="Homepage Banner",
        available_slots=5,
    )
    """

    name: str = pydantic.Field()
    """
    Name of the placement
    """

    available_slots: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="availableSlots"),
        pydantic.Field(alias="availableSlots", description="Number of available slots (minimum 1)"),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
