# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_placement_data_union import CreatePlacementDataUnion


class CreatePlacementRequestBody(UniversalBaseModel):
    """
    Request body for creating a placement

    Examples
    --------
    from kard.organizations.placements import (
        CreatePlacementDataUnion_Placement,
        CreatePlacementRequestBody,
        CreateStandardAttributes,
    )

    CreatePlacementRequestBody(
        data=CreatePlacementDataUnion_Placement(
            attributes=CreateStandardAttributes(
                name="Homepage Banner",
                available_slots=5,
            ),
        ),
    )
    """

    data: CreatePlacementDataUnion = pydantic.Field()
    """
    Placement data for creation
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
