# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_batch_activation_slot import CreateBatchActivationSlot


class CreateGroupAttributes(UniversalBaseModel):
    """
    Attributes for creating a group placement

    Examples
    --------
    from kard.organizations.placements import (
        CreateBatchActivationSlot,
        CreateGroupAttributes,
    )

    CreateGroupAttributes(
        name="Seasonal Collection",
        slots=[
            CreateBatchActivationSlot(
                placement_id="01961e5a-f26f-7e44-ce5f-1ad7c9fb4e67",
                alias="primary",
                short_description="Seasonal picks",
            )
        ],
    )
    """

    name: str = pydantic.Field()
    """
    Name of the placement
    """

    slots: typing.List[CreateBatchActivationSlot] = pydantic.Field()
    """
    Slots that make up the group
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
