# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from .placement_status import PlacementStatus


class CreateStandardAttributes(UniversalBaseModel):
    """
    Attributes for creating a standard placement

    Examples
    --------
    from kard.organizations.placements import CreateStandardAttributes

    CreateStandardAttributes(
        name="Homepage Banner",
        available_slots=5,
    )
    """

    name: str = pydantic.Field()
    """
    Name of the placement
    """

    status: typing.Optional[PlacementStatus] = pydantic.Field(default=None)
    """
    Placement status. Defaults to ACTIVE on create; when omitted on update, the current status is preserved.
    """

    available_slots: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="availableSlots"),
        pydantic.Field(alias="availableSlots", description="Number of available slots (minimum 1)"),
    ]
    content_strategy_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="contentStrategyId"),
        pydantic.Field(alias="contentStrategyId", description="ID of the content strategy to link this placement to"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
