# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_group_attributes import CreateGroupAttributes


class CreateGroupPlacementData(UniversalBaseModel):
    """
    Data for creating a group placement
    """

    attributes: CreateGroupAttributes = pydantic.Field()
    """
    Group placement attributes for creation
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
