# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_main_page_attributes import CreateMainPageAttributes
from .create_push_notification_attributes import CreatePushNotificationAttributes


class CreatePlacementDataUnion_PlacementMainPage(UniversalBaseModel):
    """
    Discriminated union for creating a placement
    """

    type: typing.Literal["placementMainPage"] = "placementMainPage"
    attributes: CreateMainPageAttributes

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class CreatePlacementDataUnion_PlacementPushNotification(UniversalBaseModel):
    """
    Discriminated union for creating a placement
    """

    type: typing.Literal["placementPushNotification"] = "placementPushNotification"
    attributes: CreatePushNotificationAttributes

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


CreatePlacementDataUnion = typing_extensions.Annotated[
    typing.Union[CreatePlacementDataUnion_PlacementMainPage, CreatePlacementDataUnion_PlacementPushNotification],
    pydantic.Field(discriminator="type"),
]
