# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata


class CreateBatchActivationSlot(UniversalBaseModel):
    """
    A slot in a batch-activation placement at creation time
    """

    content_strategy_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="contentStrategyId"),
        pydantic.Field(alias="contentStrategyId", description="ID of the content strategy that fills this slot"),
    ]
    alias: str = pydantic.Field()
    """
    Customer-defined alias for the slot, unique within the placement
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
