# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_email_attributes import CreateEmailAttributes


class CreateEmailPlacementData(UniversalBaseModel):
    """
    Data for creating an email placement
    """

    attributes: CreateEmailAttributes = pydantic.Field()
    """
    Email placement attributes for creation
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
