# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_batch_activation_attributes import CreateBatchActivationAttributes
from .create_email_attributes import CreateEmailAttributes
from .create_group_attributes import CreateGroupAttributes
from .create_push_notification_attributes import CreatePushNotificationAttributes
from .create_standard_attributes import CreateStandardAttributes


class CreatePlacementDataUnion_Placement(UniversalBaseModel):
    """
    Discriminated union for creating a placement
    """

    type: typing.Literal["placement"] = "placement"
    attributes: CreateStandardAttributes

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class CreatePlacementDataUnion_PlacementPushNotification(UniversalBaseModel):
    """
    Discriminated union for creating a placement
    """

    type: typing.Literal["placementPushNotification"] = "placementPushNotification"
    attributes: CreatePushNotificationAttributes

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class CreatePlacementDataUnion_PlacementEmail(UniversalBaseModel):
    """
    Discriminated union for creating a placement
    """

    type: typing.Literal["placementEmail"] = "placementEmail"
    attributes: CreateEmailAttributes

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class CreatePlacementDataUnion_PlacementBatchActivation(UniversalBaseModel):
    """
    Discriminated union for creating a placement
    """

    type: typing.Literal["placementBatchActivation"] = "placementBatchActivation"
    attributes: CreateBatchActivationAttributes

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class CreatePlacementDataUnion_PlacementGroup(UniversalBaseModel):
    """
    Discriminated union for creating a placement
    """

    type: typing.Literal["placementGroup"] = "placementGroup"
    attributes: CreateGroupAttributes

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


CreatePlacementDataUnion = typing_extensions.Annotated[
    typing.Union[
        CreatePlacementDataUnion_Placement,
        CreatePlacementDataUnion_PlacementPushNotification,
        CreatePlacementDataUnion_PlacementEmail,
        CreatePlacementDataUnion_PlacementBatchActivation,
        CreatePlacementDataUnion_PlacementGroup,
    ],
    pydantic.Field(discriminator="type"),
]
