# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .group_placement_attributes import GroupPlacementAttributes
from .slotted_placement_relationships import SlottedPlacementRelationships


class GroupPlacementData(UniversalBaseModel):
    """
    Group placement resource data
    """

    id: str = pydantic.Field()
    """
    Unique identifier of the placement (UUID v7)
    """

    attributes: GroupPlacementAttributes
    relationships: SlottedPlacementRelationships = pydantic.Field()
    """
    JSON:API relationships for the placement. Always present on a group placement; the `slots` to-many relationship lists the slot resource identifiers.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
