# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...content_strategies.types.content_strategy_attributes import ContentStrategyAttributes
from .batch_activation_slot_attributes import BatchActivationSlotAttributes
from .batch_activation_slot_relationships import BatchActivationSlotRelationships
from .email_placement_attributes import EmailPlacementAttributes
from .placement_attributes import PlacementAttributes
from .placement_relationships import PlacementRelationships
from .push_notification_placement_attributes import PushNotificationPlacementAttributes


class IncludedResource_ContentStrategy(UniversalBaseModel):
    """
    Discriminated union of every resource type that can appear in the `included` array. The shape of each branch matches the corresponding primary-data resource (same attributes and relationships), keyed on the JSON:API `type` discriminant.
    """

    type: typing.Literal["contentStrategy"] = "contentStrategy"
    id: str
    attributes: ContentStrategyAttributes

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class IncludedResource_BatchActivationSlot(UniversalBaseModel):
    """
    Discriminated union of every resource type that can appear in the `included` array. The shape of each branch matches the corresponding primary-data resource (same attributes and relationships), keyed on the JSON:API `type` discriminant.
    """

    type: typing.Literal["batchActivationSlot"] = "batchActivationSlot"
    id: str
    attributes: BatchActivationSlotAttributes
    relationships: BatchActivationSlotRelationships

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class IncludedResource_Placement(UniversalBaseModel):
    """
    Discriminated union of every resource type that can appear in the `included` array. The shape of each branch matches the corresponding primary-data resource (same attributes and relationships), keyed on the JSON:API `type` discriminant.
    """

    type: typing.Literal["placement"] = "placement"
    id: str
    attributes: PlacementAttributes
    relationships: typing.Optional[PlacementRelationships] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class IncludedResource_PlacementPushNotification(UniversalBaseModel):
    """
    Discriminated union of every resource type that can appear in the `included` array. The shape of each branch matches the corresponding primary-data resource (same attributes and relationships), keyed on the JSON:API `type` discriminant.
    """

    type: typing.Literal["placementPushNotification"] = "placementPushNotification"
    id: str
    attributes: PushNotificationPlacementAttributes
    relationships: typing.Optional[PlacementRelationships] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class IncludedResource_PlacementEmail(UniversalBaseModel):
    """
    Discriminated union of every resource type that can appear in the `included` array. The shape of each branch matches the corresponding primary-data resource (same attributes and relationships), keyed on the JSON:API `type` discriminant.
    """

    type: typing.Literal["placementEmail"] = "placementEmail"
    id: str
    attributes: EmailPlacementAttributes
    relationships: typing.Optional[PlacementRelationships] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


IncludedResource = typing_extensions.Annotated[
    typing.Union[
        IncludedResource_ContentStrategy,
        IncludedResource_BatchActivationSlot,
        IncludedResource_Placement,
        IncludedResource_PlacementPushNotification,
        IncludedResource_PlacementEmail,
    ],
    pydantic.Field(discriminator="type"),
]
