# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .main_page_placement_attributes import MainPagePlacementAttributes
from .placement_relationships import PlacementRelationships


class MainPagePlacementData(UniversalBaseModel):
    """
    Main-page placement resource data
    """

    id: str = pydantic.Field()
    """
    Unique identifier of the placement (UUID v7)
    """

    attributes: MainPagePlacementAttributes
    relationships: typing.Optional[PlacementRelationships] = pydantic.Field(default=None)
    """
    JSON:API relationships for the placement. Omitted entirely when the placement has no linked resources.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
