# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...content_strategies.types.content_strategy_response import ContentStrategyResponse
from .placement_format_union import PlacementFormatUnion


class PlacementResource(UniversalBaseModel):
    """
    Single placement document, optionally with embedded related resources
    """

    data: PlacementFormatUnion = pydantic.Field()
    """
    Placement resource
    """

    included: typing.Optional[typing.List[ContentStrategyResponse]] = pydantic.Field(default=None)
    """
    Related resources requested via the `include` query parameter. Only populated when `include=contentStrategy` is supplied and the placement is linked to a content strategy.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
