# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .batch_activation_placement_attributes import BatchActivationPlacementAttributes
from .email_placement_attributes import EmailPlacementAttributes
from .group_placement_attributes import GroupPlacementAttributes
from .placement_attributes import PlacementAttributes
from .placement_relationships import PlacementRelationships
from .push_notification_placement_attributes import PushNotificationPlacementAttributes
from .slotted_placement_relationships import SlottedPlacementRelationships


class PlacementFormatUnion_Placement(UniversalBaseModel):
    """
    Discriminated union for placement resources keyed on type

    Examples
    --------
    from kard.organizations.placements import (
        PlacementAttributes,
        PlacementFormatUnion_Placement,
    )

    PlacementFormatUnion_Placement(
        id="01961e5a-b74c-7d42-8456-d3a1f2c90e71",
        attributes=PlacementAttributes(
            name="Homepage Banner",
            organization_id="org-123",
            available_slots=5,
        ),
    )
    """

    type: typing.Literal["placement"] = "placement"
    id: str
    attributes: PlacementAttributes
    relationships: typing.Optional[PlacementRelationships] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class PlacementFormatUnion_PlacementPushNotification(UniversalBaseModel):
    """
    Discriminated union for placement resources keyed on type

    Examples
    --------
    from kard.organizations.placements import (
        PlacementAttributes,
        PlacementFormatUnion_Placement,
    )

    PlacementFormatUnion_Placement(
        id="01961e5a-b74c-7d42-8456-d3a1f2c90e71",
        attributes=PlacementAttributes(
            name="Homepage Banner",
            organization_id="org-123",
            available_slots=5,
        ),
    )
    """

    type: typing.Literal["placementPushNotification"] = "placementPushNotification"
    id: str
    attributes: PushNotificationPlacementAttributes
    relationships: typing.Optional[PlacementRelationships] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class PlacementFormatUnion_PlacementEmail(UniversalBaseModel):
    """
    Discriminated union for placement resources keyed on type

    Examples
    --------
    from kard.organizations.placements import (
        PlacementAttributes,
        PlacementFormatUnion_Placement,
    )

    PlacementFormatUnion_Placement(
        id="01961e5a-b74c-7d42-8456-d3a1f2c90e71",
        attributes=PlacementAttributes(
            name="Homepage Banner",
            organization_id="org-123",
            available_slots=5,
        ),
    )
    """

    type: typing.Literal["placementEmail"] = "placementEmail"
    id: str
    attributes: EmailPlacementAttributes
    relationships: typing.Optional[PlacementRelationships] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class PlacementFormatUnion_PlacementBatchActivation(UniversalBaseModel):
    """
    Discriminated union for placement resources keyed on type

    Examples
    --------
    from kard.organizations.placements import (
        PlacementAttributes,
        PlacementFormatUnion_Placement,
    )

    PlacementFormatUnion_Placement(
        id="01961e5a-b74c-7d42-8456-d3a1f2c90e71",
        attributes=PlacementAttributes(
            name="Homepage Banner",
            organization_id="org-123",
            available_slots=5,
        ),
    )
    """

    type: typing.Literal["placementBatchActivation"] = "placementBatchActivation"
    id: str
    attributes: BatchActivationPlacementAttributes
    relationships: SlottedPlacementRelationships

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class PlacementFormatUnion_PlacementGroup(UniversalBaseModel):
    """
    Discriminated union for placement resources keyed on type

    Examples
    --------
    from kard.organizations.placements import (
        PlacementAttributes,
        PlacementFormatUnion_Placement,
    )

    PlacementFormatUnion_Placement(
        id="01961e5a-b74c-7d42-8456-d3a1f2c90e71",
        attributes=PlacementAttributes(
            name="Homepage Banner",
            organization_id="org-123",
            available_slots=5,
        ),
    )
    """

    type: typing.Literal["placementGroup"] = "placementGroup"
    id: str
    attributes: GroupPlacementAttributes
    relationships: SlottedPlacementRelationships

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


"""
from kard.organizations.placements import (
    PlacementAttributes,
    PlacementFormatUnion_Placement,
)

PlacementFormatUnion_Placement(
    id="01961e5a-b74c-7d42-8456-d3a1f2c90e71",
    attributes=PlacementAttributes(
        name="Homepage Banner",
        organization_id="org-123",
        available_slots=5,
    ),
)
"""
PlacementFormatUnion = typing_extensions.Annotated[
    typing.Union[
        PlacementFormatUnion_Placement,
        PlacementFormatUnion_PlacementPushNotification,
        PlacementFormatUnion_PlacementEmail,
        PlacementFormatUnion_PlacementBatchActivation,
        PlacementFormatUnion_PlacementGroup,
    ],
    pydantic.Field(discriminator="type"),
]
