# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....commons.types.links import Links
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....internal_organizations.types.organization_pagination_metadata import OrganizationPaginationMetadata
from .included_resource import IncludedResource
from .placement_format_union import PlacementFormatUnion


class PlacementListResponse(UniversalBaseModel):
    """
    Paginated list of placements
    """

    data: typing.List[PlacementFormatUnion] = pydantic.Field()
    """
    Array of placement resources
    """

    included: typing.Optional[typing.List[IncludedResource]] = pydantic.Field(default=None)
    """
    Related resources requested via the `include` query parameter. Each entry is keyed by its `type` discriminant (`contentStrategy`, `batchActivationSlot`, `placementMainPage`, `placementPushNotification`).
    """

    links: typing.Optional[Links] = None
    meta: typing.Optional[OrganizationPaginationMetadata] = pydantic.Field(default=None)
    """
    Pagination metadata
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
