# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from .cadence import Cadence


class PushNotificationPlacementAttributes(UniversalBaseModel):
    """
    Attributes for a push-notification placement
    """

    name: str = pydantic.Field()
    """
    Name of the placement
    """

    organization_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="organizationId"),
        pydantic.Field(alias="organizationId", description="ID of the organization this placement belongs to"),
    ]
    cadence: Cadence = pydantic.Field()
    """
    Delivery cadence for the notification
    """

    created_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="When the placement was created (ISO 8601 UTC)"),
    ]
    last_modified: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="lastModified"),
        pydantic.Field(alias="lastModified", description="When the placement was last modified (ISO 8601 UTC)"),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
