# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .push_notification_placement_attributes import PushNotificationPlacementAttributes


class PushNotificationPlacementData(UniversalBaseModel):
    """
    Push-notification placement resource data
    """

    id: str = pydantic.Field()
    """
    Unique identifier of the placement (UUID v7)
    """

    attributes: PushNotificationPlacementAttributes

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
