# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ResourceIdentifier(UniversalBaseModel):
    """
    A reference to another resource by type and id.
    """

    type: str = pydantic.Field()
    """
    Discriminant of the referenced resource (e.g. `contentStrategy`).
    """

    id: str = pydantic.Field()
    """
    Identifier of the referenced resource.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
