# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .resource_identifier import ResourceIdentifier


class ToManyRelationship(UniversalBaseModel):
    """
    A JSON:API to-many relationship payload.
    """

    data: typing.List[ResourceIdentifier] = pydantic.Field()
    """
    The linked resource identifiers.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
