# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .resource_identifier import ResourceIdentifier


class ToOneRelationship(UniversalBaseModel):
    """
    A JSON:API to-one relationship payload.
    """

    data: typing.Optional[ResourceIdentifier] = pydantic.Field(default=None)
    """
    The linked resource identifier, or null when the relationship is present but unlinked.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
