# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .update_placement_data_union import UpdatePlacementDataUnion


class UpdatePlacementRequestBody(UniversalBaseModel):
    """
    Request body for updating a placement
    """

    data: UpdatePlacementDataUnion = pydantic.Field()
    """
    Placement data for update
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
