# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .cadence import Cadence


class UpdatePushNotificationAttributes(UniversalBaseModel):
    """
    Attributes for updating a push-notification placement. All fields are required.

    Examples
    --------
    from kard.organizations.placements import (
        Cadence,
        UpdatePushNotificationAttributes,
    )

    UpdatePushNotificationAttributes(
        name="Updated Alert",
        cadence=Cadence(
            frequency="WEEKLY",
            time_of_day="14:00",
            day_of_week="FRI",
        ),
    )
    """

    name: str = pydantic.Field()
    """
    Name of the placement
    """

    cadence: Cadence = pydantic.Field()
    """
    Delivery cadence for the notification
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
