# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .update_main_page_attributes import UpdateMainPageAttributes
from .update_push_notification_attributes import UpdatePushNotificationAttributes


class UpdatePlacementDataUnion_PlacementMainPage(UniversalBaseModel):
    """
    Discriminated union for updating a placement
    """

    type: typing.Literal["placementMainPage"] = "placementMainPage"
    attributes: UpdateMainPageAttributes

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class UpdatePlacementDataUnion_PlacementPushNotification(UniversalBaseModel):
    """
    Discriminated union for updating a placement
    """

    type: typing.Literal["placementPushNotification"] = "placementPushNotification"
    attributes: UpdatePushNotificationAttributes

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


UpdatePlacementDataUnion = typing_extensions.Annotated[
    typing.Union[UpdatePlacementDataUnion_PlacementMainPage, UpdatePlacementDataUnion_PlacementPushNotification],
    pydantic.Field(discriminator="type"),
]
