# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .update_push_notification_attributes import UpdatePushNotificationAttributes


class UpdatePushNotificationPlacementData(UniversalBaseModel):
    """
    Data for updating a push-notification placement
    """

    attributes: UpdatePushNotificationAttributes = pydantic.Field()
    """
    Push-notification placement attributes for update
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
