# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata


class UpdateStandardAttributes(UniversalBaseModel):
    """
    Attributes for updating a standard placement. All fields are required.

    Examples
    --------
    from kard.organizations.placements import UpdateStandardAttributes

    UpdateStandardAttributes(
        name="Updated Banner",
        available_slots=10,
    )
    """

    name: str = pydantic.Field()
    """
    Name of the placement
    """

    available_slots: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="availableSlots"),
        pydantic.Field(alias="availableSlots", description="Number of available slots (minimum 1)"),
    ]
    content_strategy_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="contentStrategyId"),
        pydantic.Field(
            alias="contentStrategyId",
            description="ID of the content strategy to link this placement to. Omit to clear any existing link (PUT requires the full attribute set, so a missing value unlinks the placement).",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
