# This file was auto-generated by Fern from our API Definition.

import typing

NotificationType = typing.Union[
    typing.Literal[
        "earnedRewardApproved",
        "earnedRewardSettled",
        "validTransaction",
        "failedTransaction",
        "clawback",
        "auditUpdate",
        "fileProcessingResult",
    ],
    typing.Any,
]
