# This file was auto-generated by Fern from our API Definition.

import typing

RejectedReason = typing.Union[
    typing.Literal[
        "AGGREGATOR_CARD_OVERLAP", "SETTLEMENT_REJECTED", "USER_NOT_ENROLLED", "USER_NOT_IN_AUDIENCE_SEGMENT"
    ],
    typing.Any,
]
